// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yoke/plugin/v1/codes.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_yoke_2fplugin_2fv1_2fcodes_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_yoke_2fplugin_2fv1_2fcodes_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_yoke_2fplugin_2fv1_2fcodes_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_yoke_2fplugin_2fv1_2fcodes_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_yoke_2fplugin_2fv1_2fcodes_2eproto;
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE
namespace yoke {
namespace plugin {
namespace v1 {

enum Code : int {
  CODE_UNSPECIFIED = 0,
  CODE_ADMISSION_STRUCTURAL_MALFORMED = 1,
  CODE_ADMISSION_IDENTITY_UNKNOWN_PLUGIN = 2,
  CODE_ADMISSION_IDENTITY_UNKNOWN_UNIT = 3,
  CODE_ADMISSION_STATE_DISABLED = 4,
  CODE_ADMISSION_AUTH_INVALID = 5,
  CODE_ADMISSION_AUTH_EXPIRED = 6,
  CODE_ADMISSION_AUTH_CONSUMED = 7,
  CODE_ADMISSION_COMPAT_UNSUPPORTED = 8,
  CODE_ADMISSION_CONSISTENCY_DIVERGENT = 9,
  CODE_ADMISSION_CONFLICT_UNIT_LIVE = 10,
  CODE_ADMISSION_SESSION_UNAVAILABLE = 11,
  CODE_SESSION_UNKNOWN = 12,
  CODE_SESSION_REVOKED = 13,
  CODE_SESSION_MESSAGE_MALFORMED = 14,
  CODE_SESSION_MESSAGE_DUPLICATE = 15,
  CODE_SESSION_DIRECTION = 16,
  CODE_SESSION_CORRELATION_MISSING = 17,
  CODE_SESSION_CORRELATION_UNKNOWN = 18,
  CODE_SCOPE_WITHHELD = 19,
  CODE_SCOPE_UNDECLARED = 20,
  CODE_STREAM_INACTIVE = 21,
  CODE_COMMAND_UNKNOWN = 22,
  CODE_QUERY_UNKNOWN = 23,
  Code_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Code_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Code_IsValid(int value);
constexpr Code Code_MIN = CODE_UNSPECIFIED;
constexpr Code Code_MAX = CODE_QUERY_UNKNOWN;
constexpr int Code_ARRAYSIZE = Code_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Code_descriptor();
template<typename T>
inline const std::string& Code_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Code>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Code_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Code_descriptor(), enum_t_value);
}
inline bool Code_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Code* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Code>(
    Code_descriptor(), name, value);
}
// ===================================================================


// ===================================================================

static const int kCodeFieldNumber = 50000;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::EnumValueOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  code;

// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace plugin
}  // namespace yoke

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::yoke::plugin::v1::Code> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::yoke::plugin::v1::Code>() {
  return ::yoke::plugin::v1::Code_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_yoke_2fplugin_2fv1_2fcodes_2eproto
