// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yoke/plugin/v1/codes.proto

#include "yoke/plugin/v1/codes.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace yoke {
namespace plugin {
namespace v1 {
}  // namespace v1
}  // namespace plugin
}  // namespace yoke
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_yoke_2fplugin_2fv1_2fcodes_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_yoke_2fplugin_2fv1_2fcodes_2eproto = nullptr;
const uint32_t TableStruct_yoke_2fplugin_2fv1_2fcodes_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_yoke_2fplugin_2fv1_2fcodes_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\032yoke/plugin/v1/codes.proto\022\016yoke.plugi"
  "n.v1\032 google/protobuf/descriptor.proto*\275"
  "\013\n\004Code\022\024\n\020CODE_UNSPECIFIED\020\000\022K\n#CODE_AD"
  "MISSION_STRUCTURAL_MALFORMED\020\001\032\"\202\265\030\036admi"
  "ssion.structural.malformed\022Q\n&CODE_ADMIS"
  "SION_IDENTITY_UNKNOWN_PLUGIN\020\002\032%\202\265\030!admi"
  "ssion.identity.unknown_plugin\022M\n$CODE_AD"
  "MISSION_IDENTITY_UNKNOWN_UNIT\020\003\032#\202\265\030\037adm"
  "ission.identity.unknown_unit\022\?\n\035CODE_ADM"
  "ISSION_STATE_DISABLED\020\004\032\034\202\265\030\030admission.s"
  "tate.disabled\022;\n\033CODE_ADMISSION_AUTH_INV"
  "ALID\020\005\032\032\202\265\030\026admission.auth.invalid\022;\n\033CO"
  "DE_ADMISSION_AUTH_EXPIRED\020\006\032\032\202\265\030\026admissi"
  "on.auth.expired\022=\n\034CODE_ADMISSION_AUTH_C"
  "ONSUMED\020\007\032\033\202\265\030\027admission.auth.consumed\022G"
  "\n!CODE_ADMISSION_COMPAT_UNSUPPORTED\020\010\032 \202"
  "\265\030\034admission.compat.unsupported\022M\n$CODE_"
  "ADMISSION_CONSISTENCY_DIVERGENT\020\t\032#\202\265\030\037a"
  "dmission.consistency.divergent\022G\n!CODE_A"
  "DMISSION_CONFLICT_UNIT_LIVE\020\n\032 \202\265\030\034admis"
  "sion.conflict.unit_live\022I\n\"CODE_ADMISSIO"
  "N_SESSION_UNAVAILABLE\020\013\032!\202\265\030\035admission.s"
  "ession.unavailable\022-\n\024CODE_SESSION_UNKNO"
  "WN\020\014\032\023\202\265\030\017session.unknown\022-\n\024CODE_SESSIO"
  "N_REVOKED\020\r\032\023\202\265\030\017session.revoked\022A\n\036CODE"
  "_SESSION_MESSAGE_MALFORMED\020\016\032\035\202\265\030\031sessio"
  "n.message.malformed\022A\n\036CODE_SESSION_MESS"
  "AGE_DUPLICATE\020\017\032\035\202\265\030\031session.message.dup"
  "licate\0221\n\026CODE_SESSION_DIRECTION\020\020\032\025\202\265\030\021"
  "session.direction\022E\n CODE_SESSION_CORREL"
  "ATION_MISSING\020\021\032\037\202\265\030\033session.correlation"
  ".missing\022E\n CODE_SESSION_CORRELATION_UNK"
  "NOWN\020\022\032\037\202\265\030\033session.correlation.unknown\022"
  "+\n\023CODE_SCOPE_WITHHELD\020\023\032\022\202\265\030\016scope.with"
  "held\022/\n\025CODE_SCOPE_UNDECLARED\020\024\032\024\202\265\030\020sco"
  "pe.undeclared\022-\n\024CODE_STREAM_INACTIVE\020\025\032"
  "\023\202\265\030\017stream.inactive\022-\n\024CODE_COMMAND_UNK"
  "NOWN\020\026\032\023\202\265\030\017command.unknown\022)\n\022CODE_QUER"
  "Y_UNKNOWN\020\027\032\021\202\265\030\rquery.unknown:1\n\004code\022!"
  ".google.protobuf.EnumValueOptions\030\320\206\003 \001("
  "\tB<Z:github.com/yoke-project/yoke/proto/"
  "yoke/plugin/v1;pluginv1b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_yoke_2fplugin_2fv1_2fcodes_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
};
static ::_pbi::once_flag descriptor_table_yoke_2fplugin_2fv1_2fcodes_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_yoke_2fplugin_2fv1_2fcodes_2eproto = {
    false, false, 1671, descriptor_table_protodef_yoke_2fplugin_2fv1_2fcodes_2eproto,
    "yoke/plugin/v1/codes.proto",
    &descriptor_table_yoke_2fplugin_2fv1_2fcodes_2eproto_once, descriptor_table_yoke_2fplugin_2fv1_2fcodes_2eproto_deps, 1, 0,
    schemas, file_default_instances, TableStruct_yoke_2fplugin_2fv1_2fcodes_2eproto::offsets,
    nullptr, file_level_enum_descriptors_yoke_2fplugin_2fv1_2fcodes_2eproto,
    file_level_service_descriptors_yoke_2fplugin_2fv1_2fcodes_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_yoke_2fplugin_2fv1_2fcodes_2eproto_getter() {
  return &descriptor_table_yoke_2fplugin_2fv1_2fcodes_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_yoke_2fplugin_2fv1_2fcodes_2eproto(&descriptor_table_yoke_2fplugin_2fv1_2fcodes_2eproto);
namespace yoke {
namespace plugin {
namespace v1 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Code_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_yoke_2fplugin_2fv1_2fcodes_2eproto);
  return file_level_enum_descriptors_yoke_2fplugin_2fv1_2fcodes_2eproto[0];
}
bool Code_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
      return true;
    default:
      return false;
  }
}

const std::string code_default("");
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::EnumValueOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false>
  code(kCodeFieldNumber, code_default, nullptr);

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace plugin
}  // namespace yoke
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
