// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yoke/plugin/v1/contract.proto

#include "yoke/plugin/v1/contract.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace yoke {
namespace plugin {
namespace v1 {
}  // namespace v1
}  // namespace plugin
}  // namespace yoke
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_yoke_2fplugin_2fv1_2fcontract_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_yoke_2fplugin_2fv1_2fcontract_2eproto = nullptr;
const uint32_t TableStruct_yoke_2fplugin_2fv1_2fcontract_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_yoke_2fplugin_2fv1_2fcontract_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\035yoke/plugin/v1/contract.proto\022\016yoke.pl"
  "ugin.v1*:\n\010Contract\022\030\n\024CONTRACT_UNSPECIF"
  "IED\020\000\022\024\n\020CONTRACT_VERSION\020\001B<Z:github.co"
  "m/yoke-project/yoke/proto/yoke/plugin/v1"
  ";pluginv1b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_yoke_2fplugin_2fv1_2fcontract_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_yoke_2fplugin_2fv1_2fcontract_2eproto = {
    false, false, 177, descriptor_table_protodef_yoke_2fplugin_2fv1_2fcontract_2eproto,
    "yoke/plugin/v1/contract.proto",
    &descriptor_table_yoke_2fplugin_2fv1_2fcontract_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_yoke_2fplugin_2fv1_2fcontract_2eproto::offsets,
    nullptr, file_level_enum_descriptors_yoke_2fplugin_2fv1_2fcontract_2eproto,
    file_level_service_descriptors_yoke_2fplugin_2fv1_2fcontract_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_yoke_2fplugin_2fv1_2fcontract_2eproto_getter() {
  return &descriptor_table_yoke_2fplugin_2fv1_2fcontract_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_yoke_2fplugin_2fv1_2fcontract_2eproto(&descriptor_table_yoke_2fplugin_2fv1_2fcontract_2eproto);
namespace yoke {
namespace plugin {
namespace v1 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Contract_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_yoke_2fplugin_2fv1_2fcontract_2eproto);
  return file_level_enum_descriptors_yoke_2fplugin_2fv1_2fcontract_2eproto[0];
}
bool Contract_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace plugin
}  // namespace yoke
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
