// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: yoke/plugin/v1/contract.proto
// Original file comments:
// The plugin contract's version, stated inside the contract. It is the integer a unit sends at
// registration, and it is the `v1` of this path: a contract whose two differ is rejected where the
// definitions are built.
#ifndef GRPC_yoke_2fplugin_2fv1_2fcontract_2eproto__INCLUDED
#define GRPC_yoke_2fplugin_2fv1_2fcontract_2eproto__INCLUDED

#include "yoke/plugin/v1/contract.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace yoke {
namespace plugin {
namespace v1 {

}  // namespace v1
}  // namespace plugin
}  // namespace yoke


#endif  // GRPC_yoke_2fplugin_2fv1_2fcontract_2eproto__INCLUDED
