// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yoke/plugin/v1/register.proto

#include "yoke/plugin/v1/register.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace yoke {
namespace plugin {
namespace v1 {
PROTOBUF_CONSTEXPR RegisterRequest::RegisterRequest(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.plugin_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.unit_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.token_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.artifact_version_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.language_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sdk_line_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.declared_)*/nullptr
  , /*decltype(_impl_.protocol_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RegisterRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RegisterRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RegisterRequestDefaultTypeInternal() {}
  union {
    RegisterRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RegisterRequestDefaultTypeInternal _RegisterRequest_default_instance_;
PROTOBUF_CONSTEXPR Surface::Surface(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.capabilities_)*/{}
  , /*decltype(_impl_.streams_)*/{}
  , /*decltype(_impl_.commands_)*/{}
  , /*decltype(_impl_.queries_)*/{}
  , /*decltype(_impl_.occurrences_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SurfaceDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SurfaceDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SurfaceDefaultTypeInternal() {}
  union {
    Surface _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SurfaceDefaultTypeInternal _Surface_default_instance_;
PROTOBUF_CONSTEXPR RegisterResponse::RegisterResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.code_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.session_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.granted_)*/nullptr
  , /*decltype(_impl_.withheld_)*/nullptr
  , /*decltype(_impl_.heartbeat_)*/nullptr
  , /*decltype(_impl_.outcome_)*/0
  , /*decltype(_impl_.stage_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct RegisterResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RegisterResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RegisterResponseDefaultTypeInternal() {}
  union {
    RegisterResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RegisterResponseDefaultTypeInternal _RegisterResponse_default_instance_;
PROTOBUF_CONSTEXPR HeartbeatTerms::HeartbeatTerms(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.interval_)*/nullptr
  , /*decltype(_impl_.tolerance_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct HeartbeatTermsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HeartbeatTermsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HeartbeatTermsDefaultTypeInternal() {}
  union {
    HeartbeatTerms _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HeartbeatTermsDefaultTypeInternal _HeartbeatTerms_default_instance_;
}  // namespace v1
}  // namespace plugin
}  // namespace yoke
static ::_pb::Metadata file_level_metadata_yoke_2fplugin_2fv1_2fregister_2eproto[4];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_yoke_2fplugin_2fv1_2fregister_2eproto[2];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_yoke_2fplugin_2fv1_2fregister_2eproto = nullptr;

const uint32_t TableStruct_yoke_2fplugin_2fv1_2fregister_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::RegisterRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::RegisterRequest, _impl_.plugin_),
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::RegisterRequest, _impl_.unit_),
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::RegisterRequest, _impl_.token_),
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::RegisterRequest, _impl_.protocol_),
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::RegisterRequest, _impl_.artifact_version_),
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::RegisterRequest, _impl_.language_),
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::RegisterRequest, _impl_.sdk_line_),
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::RegisterRequest, _impl_.declared_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::Surface, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::Surface, _impl_.capabilities_),
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::Surface, _impl_.streams_),
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::Surface, _impl_.commands_),
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::Surface, _impl_.queries_),
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::Surface, _impl_.occurrences_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::RegisterResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::RegisterResponse, _impl_.outcome_),
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::RegisterResponse, _impl_.stage_),
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::RegisterResponse, _impl_.code_),
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::RegisterResponse, _impl_.message_),
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::RegisterResponse, _impl_.session_id_),
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::RegisterResponse, _impl_.granted_),
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::RegisterResponse, _impl_.withheld_),
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::RegisterResponse, _impl_.heartbeat_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::HeartbeatTerms, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::HeartbeatTerms, _impl_.interval_),
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::HeartbeatTerms, _impl_.tolerance_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::yoke::plugin::v1::RegisterRequest)},
  { 14, -1, -1, sizeof(::yoke::plugin::v1::Surface)},
  { 25, -1, -1, sizeof(::yoke::plugin::v1::RegisterResponse)},
  { 39, -1, -1, sizeof(::yoke::plugin::v1::HeartbeatTerms)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::yoke::plugin::v1::_RegisterRequest_default_instance_._instance,
  &::yoke::plugin::v1::_Surface_default_instance_._instance,
  &::yoke::plugin::v1::_RegisterResponse_default_instance_._instance,
  &::yoke::plugin::v1::_HeartbeatTerms_default_instance_._instance,
};

const char descriptor_table_protodef_yoke_2fplugin_2fv1_2fregister_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\035yoke/plugin/v1/register.proto\022\016yoke.pl"
  "ugin.v1\032\036google/protobuf/duration.proto\""
  "\271\001\n\017RegisterRequest\022\016\n\006plugin\030\001 \001(\t\022\014\n\004u"
  "nit\030\002 \001(\t\022\r\n\005token\030\003 \001(\t\022\020\n\010protocol\030\004 \001"
  "(\r\022\030\n\020artifact_version\030\005 \001(\t\022\020\n\010language"
  "\030\006 \001(\t\022\020\n\010sdk_line\030\007 \001(\t\022)\n\010declared\030\010 \001"
  "(\0132\027.yoke.plugin.v1.Surface\"h\n\007Surface\022\024"
  "\n\014capabilities\030\001 \003(\t\022\017\n\007streams\030\002 \003(\t\022\020\n"
  "\010commands\030\003 \003(\t\022\017\n\007queries\030\004 \003(\t\022\023\n\013occu"
  "rrences\030\005 \003(\t\"\245\003\n\020RegisterResponse\0229\n\007ou"
  "tcome\030\001 \001(\0162(.yoke.plugin.v1.RegisterRes"
  "ponse.Outcome\022$\n\005stage\030\002 \001(\0162\025.yoke.plug"
  "in.v1.Stage\022\014\n\004code\030\003 \001(\t\022\017\n\007message\030\004 \001"
  "(\t\022\022\n\nsession_id\030\005 \001(\t\022(\n\007granted\030\006 \001(\0132"
  "\027.yoke.plugin.v1.Surface\022)\n\010withheld\030\007 \001"
  "(\0132\027.yoke.plugin.v1.Surface\0221\n\theartbeat"
  "\030\010 \001(\0132\036.yoke.plugin.v1.HeartbeatTerms\"u"
  "\n\007Outcome\022\027\n\023OUTCOME_UNSPECIFIED\020\000\022\024\n\020OU"
  "TCOME_ACCEPTED\020\001\022&\n\"OUTCOME_ACCEPTED_WIT"
  "H_RESTRICTIONS\020\002\022\023\n\017OUTCOME_REFUSED\020\003\"P\n"
  "\016HeartbeatTerms\022+\n\010interval\030\001 \001(\0132\031.goog"
  "le.protobuf.Duration\022\021\n\ttolerance\030\002 \001(\r*"
  "\217\002\n\005Stage\022\025\n\021STAGE_UNSPECIFIED\020\000\022\024\n\020STAG"
  "E_STRUCTURAL\020\001\022\022\n\016STAGE_IDENTITY\020\002\022\036\n\032ST"
  "AGE_ADMINISTRATIVE_STATE\020\003\022\030\n\024STAGE_AUTH"
  "ENTICATION\020\004\022\027\n\023STAGE_COMPATIBILITY\020\005\022!\n"
  "\035STAGE_DECLARATION_CONSISTENCY\020\006\022\027\n\023STAG"
  "E_AUTHORISATION\020\007\022\027\n\023STAGE_UNIT_CONFLICT"
  "\020\010\022\035\n\031STAGE_SESSION_PREPARATION\020\t2Y\n\010Reg"
  "ister\022M\n\010Register\022\037.yoke.plugin.v1.Regis"
  "terRequest\032 .yoke.plugin.v1.RegisterResp"
  "onseB<Z:github.com/yoke-project/yoke/pro"
  "to/yoke/plugin/v1;pluginv1b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_yoke_2fplugin_2fv1_2fregister_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fduration_2eproto,
};
static ::_pbi::once_flag descriptor_table_yoke_2fplugin_2fv1_2fregister_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_yoke_2fplugin_2fv1_2fregister_2eproto = {
    false, false, 1314, descriptor_table_protodef_yoke_2fplugin_2fv1_2fregister_2eproto,
    "yoke/plugin/v1/register.proto",
    &descriptor_table_yoke_2fplugin_2fv1_2fregister_2eproto_once, descriptor_table_yoke_2fplugin_2fv1_2fregister_2eproto_deps, 1, 4,
    schemas, file_default_instances, TableStruct_yoke_2fplugin_2fv1_2fregister_2eproto::offsets,
    file_level_metadata_yoke_2fplugin_2fv1_2fregister_2eproto, file_level_enum_descriptors_yoke_2fplugin_2fv1_2fregister_2eproto,
    file_level_service_descriptors_yoke_2fplugin_2fv1_2fregister_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_yoke_2fplugin_2fv1_2fregister_2eproto_getter() {
  return &descriptor_table_yoke_2fplugin_2fv1_2fregister_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_yoke_2fplugin_2fv1_2fregister_2eproto(&descriptor_table_yoke_2fplugin_2fv1_2fregister_2eproto);
namespace yoke {
namespace plugin {
namespace v1 {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RegisterResponse_Outcome_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_yoke_2fplugin_2fv1_2fregister_2eproto);
  return file_level_enum_descriptors_yoke_2fplugin_2fv1_2fregister_2eproto[0];
}
bool RegisterResponse_Outcome_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr RegisterResponse_Outcome RegisterResponse::OUTCOME_UNSPECIFIED;
constexpr RegisterResponse_Outcome RegisterResponse::OUTCOME_ACCEPTED;
constexpr RegisterResponse_Outcome RegisterResponse::OUTCOME_ACCEPTED_WITH_RESTRICTIONS;
constexpr RegisterResponse_Outcome RegisterResponse::OUTCOME_REFUSED;
constexpr RegisterResponse_Outcome RegisterResponse::Outcome_MIN;
constexpr RegisterResponse_Outcome RegisterResponse::Outcome_MAX;
constexpr int RegisterResponse::Outcome_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Stage_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_yoke_2fplugin_2fv1_2fregister_2eproto);
  return file_level_enum_descriptors_yoke_2fplugin_2fv1_2fregister_2eproto[1];
}
bool Stage_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class RegisterRequest::_Internal {
 public:
  static const ::yoke::plugin::v1::Surface& declared(const RegisterRequest* msg);
};

const ::yoke::plugin::v1::Surface&
RegisterRequest::_Internal::declared(const RegisterRequest* msg) {
  return *msg->_impl_.declared_;
}
RegisterRequest::RegisterRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:yoke.plugin.v1.RegisterRequest)
}
RegisterRequest::RegisterRequest(const RegisterRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RegisterRequest* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.plugin_){}
    , decltype(_impl_.unit_){}
    , decltype(_impl_.token_){}
    , decltype(_impl_.artifact_version_){}
    , decltype(_impl_.language_){}
    , decltype(_impl_.sdk_line_){}
    , decltype(_impl_.declared_){nullptr}
    , decltype(_impl_.protocol_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.plugin_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.plugin_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_plugin().empty()) {
    _this->_impl_.plugin_.Set(from._internal_plugin(), 
      _this->GetArenaForAllocation());
  }
  _impl_.unit_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.unit_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_unit().empty()) {
    _this->_impl_.unit_.Set(from._internal_unit(), 
      _this->GetArenaForAllocation());
  }
  _impl_.token_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.token_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_token().empty()) {
    _this->_impl_.token_.Set(from._internal_token(), 
      _this->GetArenaForAllocation());
  }
  _impl_.artifact_version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.artifact_version_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_artifact_version().empty()) {
    _this->_impl_.artifact_version_.Set(from._internal_artifact_version(), 
      _this->GetArenaForAllocation());
  }
  _impl_.language_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.language_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_language().empty()) {
    _this->_impl_.language_.Set(from._internal_language(), 
      _this->GetArenaForAllocation());
  }
  _impl_.sdk_line_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sdk_line_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_sdk_line().empty()) {
    _this->_impl_.sdk_line_.Set(from._internal_sdk_line(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_declared()) {
    _this->_impl_.declared_ = new ::yoke::plugin::v1::Surface(*from._impl_.declared_);
  }
  _this->_impl_.protocol_ = from._impl_.protocol_;
  // @@protoc_insertion_point(copy_constructor:yoke.plugin.v1.RegisterRequest)
}

inline void RegisterRequest::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.plugin_){}
    , decltype(_impl_.unit_){}
    , decltype(_impl_.token_){}
    , decltype(_impl_.artifact_version_){}
    , decltype(_impl_.language_){}
    , decltype(_impl_.sdk_line_){}
    , decltype(_impl_.declared_){nullptr}
    , decltype(_impl_.protocol_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.plugin_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.plugin_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.unit_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.unit_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.token_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.token_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.artifact_version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.artifact_version_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.language_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.language_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.sdk_line_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.sdk_line_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

RegisterRequest::~RegisterRequest() {
  // @@protoc_insertion_point(destructor:yoke.plugin.v1.RegisterRequest)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RegisterRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.plugin_.Destroy();
  _impl_.unit_.Destroy();
  _impl_.token_.Destroy();
  _impl_.artifact_version_.Destroy();
  _impl_.language_.Destroy();
  _impl_.sdk_line_.Destroy();
  if (this != internal_default_instance()) delete _impl_.declared_;
}

void RegisterRequest::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RegisterRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:yoke.plugin.v1.RegisterRequest)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.plugin_.ClearToEmpty();
  _impl_.unit_.ClearToEmpty();
  _impl_.token_.ClearToEmpty();
  _impl_.artifact_version_.ClearToEmpty();
  _impl_.language_.ClearToEmpty();
  _impl_.sdk_line_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.declared_ != nullptr) {
    delete _impl_.declared_;
  }
  _impl_.declared_ = nullptr;
  _impl_.protocol_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RegisterRequest::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string plugin = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_plugin();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "yoke.plugin.v1.RegisterRequest.plugin"));
        } else
          goto handle_unusual;
        continue;
      // string unit = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_unit();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "yoke.plugin.v1.RegisterRequest.unit"));
        } else
          goto handle_unusual;
        continue;
      // string token = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_token();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "yoke.plugin.v1.RegisterRequest.token"));
        } else
          goto handle_unusual;
        continue;
      // uint32 protocol = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.protocol_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string artifact_version = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_artifact_version();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "yoke.plugin.v1.RegisterRequest.artifact_version"));
        } else
          goto handle_unusual;
        continue;
      // string language = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_language();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "yoke.plugin.v1.RegisterRequest.language"));
        } else
          goto handle_unusual;
        continue;
      // string sdk_line = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          auto str = _internal_mutable_sdk_line();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "yoke.plugin.v1.RegisterRequest.sdk_line"));
        } else
          goto handle_unusual;
        continue;
      // .yoke.plugin.v1.Surface declared = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          ptr = ctx->ParseMessage(_internal_mutable_declared(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RegisterRequest::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yoke.plugin.v1.RegisterRequest)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string plugin = 1;
  if (!this->_internal_plugin().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_plugin().data(), static_cast<int>(this->_internal_plugin().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yoke.plugin.v1.RegisterRequest.plugin");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_plugin(), target);
  }

  // string unit = 2;
  if (!this->_internal_unit().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_unit().data(), static_cast<int>(this->_internal_unit().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yoke.plugin.v1.RegisterRequest.unit");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_unit(), target);
  }

  // string token = 3;
  if (!this->_internal_token().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_token().data(), static_cast<int>(this->_internal_token().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yoke.plugin.v1.RegisterRequest.token");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_token(), target);
  }

  // uint32 protocol = 4;
  if (this->_internal_protocol() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_protocol(), target);
  }

  // string artifact_version = 5;
  if (!this->_internal_artifact_version().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_artifact_version().data(), static_cast<int>(this->_internal_artifact_version().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yoke.plugin.v1.RegisterRequest.artifact_version");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_artifact_version(), target);
  }

  // string language = 6;
  if (!this->_internal_language().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_language().data(), static_cast<int>(this->_internal_language().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yoke.plugin.v1.RegisterRequest.language");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_language(), target);
  }

  // string sdk_line = 7;
  if (!this->_internal_sdk_line().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sdk_line().data(), static_cast<int>(this->_internal_sdk_line().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yoke.plugin.v1.RegisterRequest.sdk_line");
    target = stream->WriteStringMaybeAliased(
        7, this->_internal_sdk_line(), target);
  }

  // .yoke.plugin.v1.Surface declared = 8;
  if (this->_internal_has_declared()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(8, _Internal::declared(this),
        _Internal::declared(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yoke.plugin.v1.RegisterRequest)
  return target;
}

size_t RegisterRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yoke.plugin.v1.RegisterRequest)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string plugin = 1;
  if (!this->_internal_plugin().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_plugin());
  }

  // string unit = 2;
  if (!this->_internal_unit().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_unit());
  }

  // string token = 3;
  if (!this->_internal_token().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_token());
  }

  // string artifact_version = 5;
  if (!this->_internal_artifact_version().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_artifact_version());
  }

  // string language = 6;
  if (!this->_internal_language().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_language());
  }

  // string sdk_line = 7;
  if (!this->_internal_sdk_line().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sdk_line());
  }

  // .yoke.plugin.v1.Surface declared = 8;
  if (this->_internal_has_declared()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.declared_);
  }

  // uint32 protocol = 4;
  if (this->_internal_protocol() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_protocol());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RegisterRequest::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RegisterRequest::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RegisterRequest::GetClassData() const { return &_class_data_; }


void RegisterRequest::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RegisterRequest*>(&to_msg);
  auto& from = static_cast<const RegisterRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:yoke.plugin.v1.RegisterRequest)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_plugin().empty()) {
    _this->_internal_set_plugin(from._internal_plugin());
  }
  if (!from._internal_unit().empty()) {
    _this->_internal_set_unit(from._internal_unit());
  }
  if (!from._internal_token().empty()) {
    _this->_internal_set_token(from._internal_token());
  }
  if (!from._internal_artifact_version().empty()) {
    _this->_internal_set_artifact_version(from._internal_artifact_version());
  }
  if (!from._internal_language().empty()) {
    _this->_internal_set_language(from._internal_language());
  }
  if (!from._internal_sdk_line().empty()) {
    _this->_internal_set_sdk_line(from._internal_sdk_line());
  }
  if (from._internal_has_declared()) {
    _this->_internal_mutable_declared()->::yoke::plugin::v1::Surface::MergeFrom(
        from._internal_declared());
  }
  if (from._internal_protocol() != 0) {
    _this->_internal_set_protocol(from._internal_protocol());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RegisterRequest::CopyFrom(const RegisterRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yoke.plugin.v1.RegisterRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RegisterRequest::IsInitialized() const {
  return true;
}

void RegisterRequest::InternalSwap(RegisterRequest* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.plugin_, lhs_arena,
      &other->_impl_.plugin_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.unit_, lhs_arena,
      &other->_impl_.unit_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.token_, lhs_arena,
      &other->_impl_.token_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.artifact_version_, lhs_arena,
      &other->_impl_.artifact_version_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.language_, lhs_arena,
      &other->_impl_.language_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.sdk_line_, lhs_arena,
      &other->_impl_.sdk_line_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RegisterRequest, _impl_.protocol_)
      + sizeof(RegisterRequest::_impl_.protocol_)
      - PROTOBUF_FIELD_OFFSET(RegisterRequest, _impl_.declared_)>(
          reinterpret_cast<char*>(&_impl_.declared_),
          reinterpret_cast<char*>(&other->_impl_.declared_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RegisterRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_yoke_2fplugin_2fv1_2fregister_2eproto_getter, &descriptor_table_yoke_2fplugin_2fv1_2fregister_2eproto_once,
      file_level_metadata_yoke_2fplugin_2fv1_2fregister_2eproto[0]);
}

// ===================================================================

class Surface::_Internal {
 public:
};

Surface::Surface(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:yoke.plugin.v1.Surface)
}
Surface::Surface(const Surface& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Surface* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.capabilities_){from._impl_.capabilities_}
    , decltype(_impl_.streams_){from._impl_.streams_}
    , decltype(_impl_.commands_){from._impl_.commands_}
    , decltype(_impl_.queries_){from._impl_.queries_}
    , decltype(_impl_.occurrences_){from._impl_.occurrences_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:yoke.plugin.v1.Surface)
}

inline void Surface::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.capabilities_){arena}
    , decltype(_impl_.streams_){arena}
    , decltype(_impl_.commands_){arena}
    , decltype(_impl_.queries_){arena}
    , decltype(_impl_.occurrences_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Surface::~Surface() {
  // @@protoc_insertion_point(destructor:yoke.plugin.v1.Surface)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Surface::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.capabilities_.~RepeatedPtrField();
  _impl_.streams_.~RepeatedPtrField();
  _impl_.commands_.~RepeatedPtrField();
  _impl_.queries_.~RepeatedPtrField();
  _impl_.occurrences_.~RepeatedPtrField();
}

void Surface::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Surface::Clear() {
// @@protoc_insertion_point(message_clear_start:yoke.plugin.v1.Surface)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.capabilities_.Clear();
  _impl_.streams_.Clear();
  _impl_.commands_.Clear();
  _impl_.queries_.Clear();
  _impl_.occurrences_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Surface::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated string capabilities = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_capabilities();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "yoke.plugin.v1.Surface.capabilities"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated string streams = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_streams();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "yoke.plugin.v1.Surface.streams"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated string commands = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_commands();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "yoke.plugin.v1.Surface.commands"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated string queries = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_queries();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "yoke.plugin.v1.Surface.queries"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<34>(ptr));
        } else
          goto handle_unusual;
        continue;
      // repeated string occurrences = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr -= 1;
          do {
            ptr += 1;
            auto str = _internal_add_occurrences();
            ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
            CHK_(ptr);
            CHK_(::_pbi::VerifyUTF8(str, "yoke.plugin.v1.Surface.occurrences"));
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<42>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Surface::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yoke.plugin.v1.Surface)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string capabilities = 1;
  for (int i = 0, n = this->_internal_capabilities_size(); i < n; i++) {
    const auto& s = this->_internal_capabilities(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yoke.plugin.v1.Surface.capabilities");
    target = stream->WriteString(1, s, target);
  }

  // repeated string streams = 2;
  for (int i = 0, n = this->_internal_streams_size(); i < n; i++) {
    const auto& s = this->_internal_streams(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yoke.plugin.v1.Surface.streams");
    target = stream->WriteString(2, s, target);
  }

  // repeated string commands = 3;
  for (int i = 0, n = this->_internal_commands_size(); i < n; i++) {
    const auto& s = this->_internal_commands(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yoke.plugin.v1.Surface.commands");
    target = stream->WriteString(3, s, target);
  }

  // repeated string queries = 4;
  for (int i = 0, n = this->_internal_queries_size(); i < n; i++) {
    const auto& s = this->_internal_queries(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yoke.plugin.v1.Surface.queries");
    target = stream->WriteString(4, s, target);
  }

  // repeated string occurrences = 5;
  for (int i = 0, n = this->_internal_occurrences_size(); i < n; i++) {
    const auto& s = this->_internal_occurrences(i);
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      s.data(), static_cast<int>(s.length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yoke.plugin.v1.Surface.occurrences");
    target = stream->WriteString(5, s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yoke.plugin.v1.Surface)
  return target;
}

size_t Surface::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yoke.plugin.v1.Surface)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated string capabilities = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.capabilities_.size());
  for (int i = 0, n = _impl_.capabilities_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.capabilities_.Get(i));
  }

  // repeated string streams = 2;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.streams_.size());
  for (int i = 0, n = _impl_.streams_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.streams_.Get(i));
  }

  // repeated string commands = 3;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.commands_.size());
  for (int i = 0, n = _impl_.commands_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.commands_.Get(i));
  }

  // repeated string queries = 4;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.queries_.size());
  for (int i = 0, n = _impl_.queries_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.queries_.Get(i));
  }

  // repeated string occurrences = 5;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(_impl_.occurrences_.size());
  for (int i = 0, n = _impl_.occurrences_.size(); i < n; i++) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
      _impl_.occurrences_.Get(i));
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Surface::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Surface::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Surface::GetClassData() const { return &_class_data_; }


void Surface::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Surface*>(&to_msg);
  auto& from = static_cast<const Surface&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:yoke.plugin.v1.Surface)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.capabilities_.MergeFrom(from._impl_.capabilities_);
  _this->_impl_.streams_.MergeFrom(from._impl_.streams_);
  _this->_impl_.commands_.MergeFrom(from._impl_.commands_);
  _this->_impl_.queries_.MergeFrom(from._impl_.queries_);
  _this->_impl_.occurrences_.MergeFrom(from._impl_.occurrences_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Surface::CopyFrom(const Surface& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yoke.plugin.v1.Surface)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Surface::IsInitialized() const {
  return true;
}

void Surface::InternalSwap(Surface* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.capabilities_.InternalSwap(&other->_impl_.capabilities_);
  _impl_.streams_.InternalSwap(&other->_impl_.streams_);
  _impl_.commands_.InternalSwap(&other->_impl_.commands_);
  _impl_.queries_.InternalSwap(&other->_impl_.queries_);
  _impl_.occurrences_.InternalSwap(&other->_impl_.occurrences_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Surface::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_yoke_2fplugin_2fv1_2fregister_2eproto_getter, &descriptor_table_yoke_2fplugin_2fv1_2fregister_2eproto_once,
      file_level_metadata_yoke_2fplugin_2fv1_2fregister_2eproto[1]);
}

// ===================================================================

class RegisterResponse::_Internal {
 public:
  static const ::yoke::plugin::v1::Surface& granted(const RegisterResponse* msg);
  static const ::yoke::plugin::v1::Surface& withheld(const RegisterResponse* msg);
  static const ::yoke::plugin::v1::HeartbeatTerms& heartbeat(const RegisterResponse* msg);
};

const ::yoke::plugin::v1::Surface&
RegisterResponse::_Internal::granted(const RegisterResponse* msg) {
  return *msg->_impl_.granted_;
}
const ::yoke::plugin::v1::Surface&
RegisterResponse::_Internal::withheld(const RegisterResponse* msg) {
  return *msg->_impl_.withheld_;
}
const ::yoke::plugin::v1::HeartbeatTerms&
RegisterResponse::_Internal::heartbeat(const RegisterResponse* msg) {
  return *msg->_impl_.heartbeat_;
}
RegisterResponse::RegisterResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:yoke.plugin.v1.RegisterResponse)
}
RegisterResponse::RegisterResponse(const RegisterResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  RegisterResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.code_){}
    , decltype(_impl_.message_){}
    , decltype(_impl_.session_id_){}
    , decltype(_impl_.granted_){nullptr}
    , decltype(_impl_.withheld_){nullptr}
    , decltype(_impl_.heartbeat_){nullptr}
    , decltype(_impl_.outcome_){}
    , decltype(_impl_.stage_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_code().empty()) {
    _this->_impl_.code_.Set(from._internal_code(), 
      _this->GetArenaForAllocation());
  }
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message().empty()) {
    _this->_impl_.message_.Set(from._internal_message(), 
      _this->GetArenaForAllocation());
  }
  _impl_.session_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.session_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_session_id().empty()) {
    _this->_impl_.session_id_.Set(from._internal_session_id(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_granted()) {
    _this->_impl_.granted_ = new ::yoke::plugin::v1::Surface(*from._impl_.granted_);
  }
  if (from._internal_has_withheld()) {
    _this->_impl_.withheld_ = new ::yoke::plugin::v1::Surface(*from._impl_.withheld_);
  }
  if (from._internal_has_heartbeat()) {
    _this->_impl_.heartbeat_ = new ::yoke::plugin::v1::HeartbeatTerms(*from._impl_.heartbeat_);
  }
  ::memcpy(&_impl_.outcome_, &from._impl_.outcome_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.stage_) -
    reinterpret_cast<char*>(&_impl_.outcome_)) + sizeof(_impl_.stage_));
  // @@protoc_insertion_point(copy_constructor:yoke.plugin.v1.RegisterResponse)
}

inline void RegisterResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.code_){}
    , decltype(_impl_.message_){}
    , decltype(_impl_.session_id_){}
    , decltype(_impl_.granted_){nullptr}
    , decltype(_impl_.withheld_){nullptr}
    , decltype(_impl_.heartbeat_){nullptr}
    , decltype(_impl_.outcome_){0}
    , decltype(_impl_.stage_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.code_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.code_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.session_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.session_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

RegisterResponse::~RegisterResponse() {
  // @@protoc_insertion_point(destructor:yoke.plugin.v1.RegisterResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RegisterResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.code_.Destroy();
  _impl_.message_.Destroy();
  _impl_.session_id_.Destroy();
  if (this != internal_default_instance()) delete _impl_.granted_;
  if (this != internal_default_instance()) delete _impl_.withheld_;
  if (this != internal_default_instance()) delete _impl_.heartbeat_;
}

void RegisterResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void RegisterResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:yoke.plugin.v1.RegisterResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.code_.ClearToEmpty();
  _impl_.message_.ClearToEmpty();
  _impl_.session_id_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.granted_ != nullptr) {
    delete _impl_.granted_;
  }
  _impl_.granted_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.withheld_ != nullptr) {
    delete _impl_.withheld_;
  }
  _impl_.withheld_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.heartbeat_ != nullptr) {
    delete _impl_.heartbeat_;
  }
  _impl_.heartbeat_ = nullptr;
  ::memset(&_impl_.outcome_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.stage_) -
      reinterpret_cast<char*>(&_impl_.outcome_)) + sizeof(_impl_.stage_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RegisterResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .yoke.plugin.v1.RegisterResponse.Outcome outcome = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_outcome(static_cast<::yoke::plugin::v1::RegisterResponse_Outcome>(val));
        } else
          goto handle_unusual;
        continue;
      // .yoke.plugin.v1.Stage stage = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_stage(static_cast<::yoke::plugin::v1::Stage>(val));
        } else
          goto handle_unusual;
        continue;
      // string code = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_code();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "yoke.plugin.v1.RegisterResponse.code"));
        } else
          goto handle_unusual;
        continue;
      // string message = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "yoke.plugin.v1.RegisterResponse.message"));
        } else
          goto handle_unusual;
        continue;
      // string session_id = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          auto str = _internal_mutable_session_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "yoke.plugin.v1.RegisterResponse.session_id"));
        } else
          goto handle_unusual;
        continue;
      // .yoke.plugin.v1.Surface granted = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_granted(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .yoke.plugin.v1.Surface withheld = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr = ctx->ParseMessage(_internal_mutable_withheld(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .yoke.plugin.v1.HeartbeatTerms heartbeat = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          ptr = ctx->ParseMessage(_internal_mutable_heartbeat(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RegisterResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yoke.plugin.v1.RegisterResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .yoke.plugin.v1.RegisterResponse.Outcome outcome = 1;
  if (this->_internal_outcome() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_outcome(), target);
  }

  // .yoke.plugin.v1.Stage stage = 2;
  if (this->_internal_stage() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      2, this->_internal_stage(), target);
  }

  // string code = 3;
  if (!this->_internal_code().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_code().data(), static_cast<int>(this->_internal_code().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yoke.plugin.v1.RegisterResponse.code");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_code(), target);
  }

  // string message = 4;
  if (!this->_internal_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yoke.plugin.v1.RegisterResponse.message");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_message(), target);
  }

  // string session_id = 5;
  if (!this->_internal_session_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_session_id().data(), static_cast<int>(this->_internal_session_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yoke.plugin.v1.RegisterResponse.session_id");
    target = stream->WriteStringMaybeAliased(
        5, this->_internal_session_id(), target);
  }

  // .yoke.plugin.v1.Surface granted = 6;
  if (this->_internal_has_granted()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, _Internal::granted(this),
        _Internal::granted(this).GetCachedSize(), target, stream);
  }

  // .yoke.plugin.v1.Surface withheld = 7;
  if (this->_internal_has_withheld()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(7, _Internal::withheld(this),
        _Internal::withheld(this).GetCachedSize(), target, stream);
  }

  // .yoke.plugin.v1.HeartbeatTerms heartbeat = 8;
  if (this->_internal_has_heartbeat()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(8, _Internal::heartbeat(this),
        _Internal::heartbeat(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yoke.plugin.v1.RegisterResponse)
  return target;
}

size_t RegisterResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yoke.plugin.v1.RegisterResponse)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string code = 3;
  if (!this->_internal_code().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_code());
  }

  // string message = 4;
  if (!this->_internal_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  // string session_id = 5;
  if (!this->_internal_session_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_session_id());
  }

  // .yoke.plugin.v1.Surface granted = 6;
  if (this->_internal_has_granted()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.granted_);
  }

  // .yoke.plugin.v1.Surface withheld = 7;
  if (this->_internal_has_withheld()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.withheld_);
  }

  // .yoke.plugin.v1.HeartbeatTerms heartbeat = 8;
  if (this->_internal_has_heartbeat()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.heartbeat_);
  }

  // .yoke.plugin.v1.RegisterResponse.Outcome outcome = 1;
  if (this->_internal_outcome() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_outcome());
  }

  // .yoke.plugin.v1.Stage stage = 2;
  if (this->_internal_stage() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_stage());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RegisterResponse::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    RegisterResponse::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RegisterResponse::GetClassData() const { return &_class_data_; }


void RegisterResponse::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<RegisterResponse*>(&to_msg);
  auto& from = static_cast<const RegisterResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:yoke.plugin.v1.RegisterResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_code().empty()) {
    _this->_internal_set_code(from._internal_code());
  }
  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (!from._internal_session_id().empty()) {
    _this->_internal_set_session_id(from._internal_session_id());
  }
  if (from._internal_has_granted()) {
    _this->_internal_mutable_granted()->::yoke::plugin::v1::Surface::MergeFrom(
        from._internal_granted());
  }
  if (from._internal_has_withheld()) {
    _this->_internal_mutable_withheld()->::yoke::plugin::v1::Surface::MergeFrom(
        from._internal_withheld());
  }
  if (from._internal_has_heartbeat()) {
    _this->_internal_mutable_heartbeat()->::yoke::plugin::v1::HeartbeatTerms::MergeFrom(
        from._internal_heartbeat());
  }
  if (from._internal_outcome() != 0) {
    _this->_internal_set_outcome(from._internal_outcome());
  }
  if (from._internal_stage() != 0) {
    _this->_internal_set_stage(from._internal_stage());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RegisterResponse::CopyFrom(const RegisterResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yoke.plugin.v1.RegisterResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RegisterResponse::IsInitialized() const {
  return true;
}

void RegisterResponse::InternalSwap(RegisterResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.code_, lhs_arena,
      &other->_impl_.code_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_, lhs_arena,
      &other->_impl_.message_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.session_id_, lhs_arena,
      &other->_impl_.session_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RegisterResponse, _impl_.stage_)
      + sizeof(RegisterResponse::_impl_.stage_)
      - PROTOBUF_FIELD_OFFSET(RegisterResponse, _impl_.granted_)>(
          reinterpret_cast<char*>(&_impl_.granted_),
          reinterpret_cast<char*>(&other->_impl_.granted_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RegisterResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_yoke_2fplugin_2fv1_2fregister_2eproto_getter, &descriptor_table_yoke_2fplugin_2fv1_2fregister_2eproto_once,
      file_level_metadata_yoke_2fplugin_2fv1_2fregister_2eproto[2]);
}

// ===================================================================

class HeartbeatTerms::_Internal {
 public:
  static const ::PROTOBUF_NAMESPACE_ID::Duration& interval(const HeartbeatTerms* msg);
};

const ::PROTOBUF_NAMESPACE_ID::Duration&
HeartbeatTerms::_Internal::interval(const HeartbeatTerms* msg) {
  return *msg->_impl_.interval_;
}
void HeartbeatTerms::clear_interval() {
  if (GetArenaForAllocation() == nullptr && _impl_.interval_ != nullptr) {
    delete _impl_.interval_;
  }
  _impl_.interval_ = nullptr;
}
HeartbeatTerms::HeartbeatTerms(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:yoke.plugin.v1.HeartbeatTerms)
}
HeartbeatTerms::HeartbeatTerms(const HeartbeatTerms& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  HeartbeatTerms* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.interval_){nullptr}
    , decltype(_impl_.tolerance_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_interval()) {
    _this->_impl_.interval_ = new ::PROTOBUF_NAMESPACE_ID::Duration(*from._impl_.interval_);
  }
  _this->_impl_.tolerance_ = from._impl_.tolerance_;
  // @@protoc_insertion_point(copy_constructor:yoke.plugin.v1.HeartbeatTerms)
}

inline void HeartbeatTerms::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.interval_){nullptr}
    , decltype(_impl_.tolerance_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

HeartbeatTerms::~HeartbeatTerms() {
  // @@protoc_insertion_point(destructor:yoke.plugin.v1.HeartbeatTerms)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void HeartbeatTerms::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.interval_;
}

void HeartbeatTerms::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void HeartbeatTerms::Clear() {
// @@protoc_insertion_point(message_clear_start:yoke.plugin.v1.HeartbeatTerms)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.interval_ != nullptr) {
    delete _impl_.interval_;
  }
  _impl_.interval_ = nullptr;
  _impl_.tolerance_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* HeartbeatTerms::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .google.protobuf.Duration interval = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_interval(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 tolerance = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.tolerance_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* HeartbeatTerms::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yoke.plugin.v1.HeartbeatTerms)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.protobuf.Duration interval = 1;
  if (this->_internal_has_interval()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::interval(this),
        _Internal::interval(this).GetCachedSize(), target, stream);
  }

  // uint32 tolerance = 2;
  if (this->_internal_tolerance() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_tolerance(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yoke.plugin.v1.HeartbeatTerms)
  return target;
}

size_t HeartbeatTerms::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yoke.plugin.v1.HeartbeatTerms)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .google.protobuf.Duration interval = 1;
  if (this->_internal_has_interval()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.interval_);
  }

  // uint32 tolerance = 2;
  if (this->_internal_tolerance() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_tolerance());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData HeartbeatTerms::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    HeartbeatTerms::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*HeartbeatTerms::GetClassData() const { return &_class_data_; }


void HeartbeatTerms::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<HeartbeatTerms*>(&to_msg);
  auto& from = static_cast<const HeartbeatTerms&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:yoke.plugin.v1.HeartbeatTerms)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_interval()) {
    _this->_internal_mutable_interval()->::PROTOBUF_NAMESPACE_ID::Duration::MergeFrom(
        from._internal_interval());
  }
  if (from._internal_tolerance() != 0) {
    _this->_internal_set_tolerance(from._internal_tolerance());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void HeartbeatTerms::CopyFrom(const HeartbeatTerms& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yoke.plugin.v1.HeartbeatTerms)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HeartbeatTerms::IsInitialized() const {
  return true;
}

void HeartbeatTerms::InternalSwap(HeartbeatTerms* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(HeartbeatTerms, _impl_.tolerance_)
      + sizeof(HeartbeatTerms::_impl_.tolerance_)
      - PROTOBUF_FIELD_OFFSET(HeartbeatTerms, _impl_.interval_)>(
          reinterpret_cast<char*>(&_impl_.interval_),
          reinterpret_cast<char*>(&other->_impl_.interval_));
}

::PROTOBUF_NAMESPACE_ID::Metadata HeartbeatTerms::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_yoke_2fplugin_2fv1_2fregister_2eproto_getter, &descriptor_table_yoke_2fplugin_2fv1_2fregister_2eproto_once,
      file_level_metadata_yoke_2fplugin_2fv1_2fregister_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace plugin
}  // namespace yoke
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::yoke::plugin::v1::RegisterRequest*
Arena::CreateMaybeMessage< ::yoke::plugin::v1::RegisterRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yoke::plugin::v1::RegisterRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::yoke::plugin::v1::Surface*
Arena::CreateMaybeMessage< ::yoke::plugin::v1::Surface >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yoke::plugin::v1::Surface >(arena);
}
template<> PROTOBUF_NOINLINE ::yoke::plugin::v1::RegisterResponse*
Arena::CreateMaybeMessage< ::yoke::plugin::v1::RegisterResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yoke::plugin::v1::RegisterResponse >(arena);
}
template<> PROTOBUF_NOINLINE ::yoke::plugin::v1::HeartbeatTerms*
Arena::CreateMaybeMessage< ::yoke::plugin::v1::HeartbeatTerms >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yoke::plugin::v1::HeartbeatTerms >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
