// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: yoke/plugin/v1/register.proto

#include "yoke/plugin/v1/register.pb.h"
#include "yoke/plugin/v1/register.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace yoke {
namespace plugin {
namespace v1 {

static const char* Register_method_names[] = {
  "/yoke.plugin.v1.Register/Register",
};

std::unique_ptr< Register::Stub> Register::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Register::Stub> stub(new Register::Stub(channel, options));
  return stub;
}

Register::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Register_(Register_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Register::Stub::Register(::grpc::ClientContext* context, const ::yoke::plugin::v1::RegisterRequest& request, ::yoke::plugin::v1::RegisterResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::yoke::plugin::v1::RegisterRequest, ::yoke::plugin::v1::RegisterResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Register_, context, request, response);
}

void Register::Stub::async::Register(::grpc::ClientContext* context, const ::yoke::plugin::v1::RegisterRequest* request, ::yoke::plugin::v1::RegisterResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::yoke::plugin::v1::RegisterRequest, ::yoke::plugin::v1::RegisterResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Register_, context, request, response, std::move(f));
}

void Register::Stub::async::Register(::grpc::ClientContext* context, const ::yoke::plugin::v1::RegisterRequest* request, ::yoke::plugin::v1::RegisterResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Register_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::yoke::plugin::v1::RegisterResponse>* Register::Stub::PrepareAsyncRegisterRaw(::grpc::ClientContext* context, const ::yoke::plugin::v1::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::yoke::plugin::v1::RegisterResponse, ::yoke::plugin::v1::RegisterRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Register_, context, request);
}

::grpc::ClientAsyncResponseReader< ::yoke::plugin::v1::RegisterResponse>* Register::Stub::AsyncRegisterRaw(::grpc::ClientContext* context, const ::yoke::plugin::v1::RegisterRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRegisterRaw(context, request, cq);
  result->StartCall();
  return result;
}

Register::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Register_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Register::Service, ::yoke::plugin::v1::RegisterRequest, ::yoke::plugin::v1::RegisterResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Register::Service* service,
             ::grpc::ServerContext* ctx,
             const ::yoke::plugin::v1::RegisterRequest* req,
             ::yoke::plugin::v1::RegisterResponse* resp) {
               return service->Register(ctx, req, resp);
             }, this)));
}

Register::Service::~Service() {
}

::grpc::Status Register::Service::Register(::grpc::ServerContext* context, const ::yoke::plugin::v1::RegisterRequest* request, ::yoke::plugin::v1::RegisterResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace yoke
}  // namespace plugin
}  // namespace v1

