// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yoke/plugin/v1/session.proto

#include "yoke/plugin/v1/session.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace yoke {
namespace plugin {
namespace v1 {
PROTOBUF_CONSTEXPR Envelope::Envelope(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.message_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.session_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.correlation_id_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.sent_at_unix_nano_)*/int64_t{0}
  , /*decltype(_impl_.payload_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct EnvelopeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR EnvelopeDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~EnvelopeDefaultTypeInternal() {}
  union {
    Envelope _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 EnvelopeDefaultTypeInternal _Envelope_default_instance_;
}  // namespace v1
}  // namespace plugin
}  // namespace yoke
static ::_pb::Metadata file_level_metadata_yoke_2fplugin_2fv1_2fsession_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_yoke_2fplugin_2fv1_2fsession_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_yoke_2fplugin_2fv1_2fsession_2eproto = nullptr;

const uint32_t TableStruct_yoke_2fplugin_2fv1_2fsession_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::Envelope, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::Envelope, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::Envelope, _impl_.message_id_),
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::Envelope, _impl_.session_id_),
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::Envelope, _impl_.sent_at_unix_nano_),
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::Envelope, _impl_.correlation_id_),
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::yoke::plugin::v1::Envelope, _impl_.payload_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::yoke::plugin::v1::Envelope)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::yoke::plugin::v1::_Envelope_default_instance_._instance,
};

const char descriptor_table_protodef_yoke_2fplugin_2fv1_2fsession_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\034yoke/plugin/v1/session.proto\022\016yoke.plu"
  "gin.v1\032\035yoke/plugin/v1/families.proto\"\273\003"
  "\n\010Envelope\022\022\n\nmessage_id\030\001 \001(\t\022\022\n\nsessio"
  "n_id\030\002 \001(\t\022\031\n\021sent_at_unix_nano\030\003 \001(\003\022\026\n"
  "\016correlation_id\030\004 \001(\t\0221\n\007session\030\005 \001(\0132\036"
  ".yoke.plugin.v1.SessionMessageH\000\022*\n\007cont"
  "rol\030\006 \001(\0132\027.yoke.plugin.v1.ControlH\000\022\"\n\003"
  "ack\030\007 \001(\0132\023.yoke.plugin.v1.AckH\000\022&\n\005quer"
  "y\030\010 \001(\0132\025.yoke.plugin.v1.QueryH\000\022$\n\004data"
  "\030\t \001(\0132\024.yoke.plugin.v1.DataH\000\022(\n\006health"
  "\030\n \001(\0132\026.yoke.plugin.v1.HealthH\000\022&\n\005even"
  "t\030\013 \001(\0132\025.yoke.plugin.v1.EventH\000\022&\n\005erro"
  "r\030\014 \001(\0132\025.yoke.plugin.v1.ErrorH\000B\t\n\007payl"
  "oad2I\n\007Session\022>\n\004Open\022\030.yoke.plugin.v1."
  "Envelope\032\030.yoke.plugin.v1.Envelope(\0010\001B<"
  "Z:github.com/yoke-project/yoke/proto/yok"
  "e/plugin/v1;pluginv1b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_yoke_2fplugin_2fv1_2fsession_2eproto_deps[1] = {
  &::descriptor_table_yoke_2fplugin_2fv1_2ffamilies_2eproto,
};
static ::_pbi::once_flag descriptor_table_yoke_2fplugin_2fv1_2fsession_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_yoke_2fplugin_2fv1_2fsession_2eproto = {
    false, false, 668, descriptor_table_protodef_yoke_2fplugin_2fv1_2fsession_2eproto,
    "yoke/plugin/v1/session.proto",
    &descriptor_table_yoke_2fplugin_2fv1_2fsession_2eproto_once, descriptor_table_yoke_2fplugin_2fv1_2fsession_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_yoke_2fplugin_2fv1_2fsession_2eproto::offsets,
    file_level_metadata_yoke_2fplugin_2fv1_2fsession_2eproto, file_level_enum_descriptors_yoke_2fplugin_2fv1_2fsession_2eproto,
    file_level_service_descriptors_yoke_2fplugin_2fv1_2fsession_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_yoke_2fplugin_2fv1_2fsession_2eproto_getter() {
  return &descriptor_table_yoke_2fplugin_2fv1_2fsession_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_yoke_2fplugin_2fv1_2fsession_2eproto(&descriptor_table_yoke_2fplugin_2fv1_2fsession_2eproto);
namespace yoke {
namespace plugin {
namespace v1 {

// ===================================================================

class Envelope::_Internal {
 public:
  static const ::yoke::plugin::v1::SessionMessage& session(const Envelope* msg);
  static const ::yoke::plugin::v1::Control& control(const Envelope* msg);
  static const ::yoke::plugin::v1::Ack& ack(const Envelope* msg);
  static const ::yoke::plugin::v1::Query& query(const Envelope* msg);
  static const ::yoke::plugin::v1::Data& data(const Envelope* msg);
  static const ::yoke::plugin::v1::Health& health(const Envelope* msg);
  static const ::yoke::plugin::v1::Event& event(const Envelope* msg);
  static const ::yoke::plugin::v1::Error& error(const Envelope* msg);
};

const ::yoke::plugin::v1::SessionMessage&
Envelope::_Internal::session(const Envelope* msg) {
  return *msg->_impl_.payload_.session_;
}
const ::yoke::plugin::v1::Control&
Envelope::_Internal::control(const Envelope* msg) {
  return *msg->_impl_.payload_.control_;
}
const ::yoke::plugin::v1::Ack&
Envelope::_Internal::ack(const Envelope* msg) {
  return *msg->_impl_.payload_.ack_;
}
const ::yoke::plugin::v1::Query&
Envelope::_Internal::query(const Envelope* msg) {
  return *msg->_impl_.payload_.query_;
}
const ::yoke::plugin::v1::Data&
Envelope::_Internal::data(const Envelope* msg) {
  return *msg->_impl_.payload_.data_;
}
const ::yoke::plugin::v1::Health&
Envelope::_Internal::health(const Envelope* msg) {
  return *msg->_impl_.payload_.health_;
}
const ::yoke::plugin::v1::Event&
Envelope::_Internal::event(const Envelope* msg) {
  return *msg->_impl_.payload_.event_;
}
const ::yoke::plugin::v1::Error&
Envelope::_Internal::error(const Envelope* msg) {
  return *msg->_impl_.payload_.error_;
}
void Envelope::set_allocated_session(::yoke::plugin::v1::SessionMessage* session) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (session) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(session));
    if (message_arena != submessage_arena) {
      session = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, session, submessage_arena);
    }
    set_has_session();
    _impl_.payload_.session_ = session;
  }
  // @@protoc_insertion_point(field_set_allocated:yoke.plugin.v1.Envelope.session)
}
void Envelope::clear_session() {
  if (_internal_has_session()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.session_;
    }
    clear_has_payload();
  }
}
void Envelope::set_allocated_control(::yoke::plugin::v1::Control* control) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (control) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(control));
    if (message_arena != submessage_arena) {
      control = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, control, submessage_arena);
    }
    set_has_control();
    _impl_.payload_.control_ = control;
  }
  // @@protoc_insertion_point(field_set_allocated:yoke.plugin.v1.Envelope.control)
}
void Envelope::clear_control() {
  if (_internal_has_control()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.control_;
    }
    clear_has_payload();
  }
}
void Envelope::set_allocated_ack(::yoke::plugin::v1::Ack* ack) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (ack) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(ack));
    if (message_arena != submessage_arena) {
      ack = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, ack, submessage_arena);
    }
    set_has_ack();
    _impl_.payload_.ack_ = ack;
  }
  // @@protoc_insertion_point(field_set_allocated:yoke.plugin.v1.Envelope.ack)
}
void Envelope::clear_ack() {
  if (_internal_has_ack()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.ack_;
    }
    clear_has_payload();
  }
}
void Envelope::set_allocated_query(::yoke::plugin::v1::Query* query) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (query) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(query));
    if (message_arena != submessage_arena) {
      query = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, query, submessage_arena);
    }
    set_has_query();
    _impl_.payload_.query_ = query;
  }
  // @@protoc_insertion_point(field_set_allocated:yoke.plugin.v1.Envelope.query)
}
void Envelope::clear_query() {
  if (_internal_has_query()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.query_;
    }
    clear_has_payload();
  }
}
void Envelope::set_allocated_data(::yoke::plugin::v1::Data* data) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (data) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(data));
    if (message_arena != submessage_arena) {
      data = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, data, submessage_arena);
    }
    set_has_data();
    _impl_.payload_.data_ = data;
  }
  // @@protoc_insertion_point(field_set_allocated:yoke.plugin.v1.Envelope.data)
}
void Envelope::clear_data() {
  if (_internal_has_data()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.data_;
    }
    clear_has_payload();
  }
}
void Envelope::set_allocated_health(::yoke::plugin::v1::Health* health) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (health) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(health));
    if (message_arena != submessage_arena) {
      health = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, health, submessage_arena);
    }
    set_has_health();
    _impl_.payload_.health_ = health;
  }
  // @@protoc_insertion_point(field_set_allocated:yoke.plugin.v1.Envelope.health)
}
void Envelope::clear_health() {
  if (_internal_has_health()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.health_;
    }
    clear_has_payload();
  }
}
void Envelope::set_allocated_event(::yoke::plugin::v1::Event* event) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (event) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(event));
    if (message_arena != submessage_arena) {
      event = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, event, submessage_arena);
    }
    set_has_event();
    _impl_.payload_.event_ = event;
  }
  // @@protoc_insertion_point(field_set_allocated:yoke.plugin.v1.Envelope.event)
}
void Envelope::clear_event() {
  if (_internal_has_event()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.event_;
    }
    clear_has_payload();
  }
}
void Envelope::set_allocated_error(::yoke::plugin::v1::Error* error) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_payload();
  if (error) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(error));
    if (message_arena != submessage_arena) {
      error = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, error, submessage_arena);
    }
    set_has_error();
    _impl_.payload_.error_ = error;
  }
  // @@protoc_insertion_point(field_set_allocated:yoke.plugin.v1.Envelope.error)
}
void Envelope::clear_error() {
  if (_internal_has_error()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.payload_.error_;
    }
    clear_has_payload();
  }
}
Envelope::Envelope(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:yoke.plugin.v1.Envelope)
}
Envelope::Envelope(const Envelope& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Envelope* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.message_id_){}
    , decltype(_impl_.session_id_){}
    , decltype(_impl_.correlation_id_){}
    , decltype(_impl_.sent_at_unix_nano_){}
    , decltype(_impl_.payload_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.message_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message_id().empty()) {
    _this->_impl_.message_id_.Set(from._internal_message_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.session_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.session_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_session_id().empty()) {
    _this->_impl_.session_id_.Set(from._internal_session_id(), 
      _this->GetArenaForAllocation());
  }
  _impl_.correlation_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.correlation_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_correlation_id().empty()) {
    _this->_impl_.correlation_id_.Set(from._internal_correlation_id(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.sent_at_unix_nano_ = from._impl_.sent_at_unix_nano_;
  clear_has_payload();
  switch (from.payload_case()) {
    case kSession: {
      _this->_internal_mutable_session()->::yoke::plugin::v1::SessionMessage::MergeFrom(
          from._internal_session());
      break;
    }
    case kControl: {
      _this->_internal_mutable_control()->::yoke::plugin::v1::Control::MergeFrom(
          from._internal_control());
      break;
    }
    case kAck: {
      _this->_internal_mutable_ack()->::yoke::plugin::v1::Ack::MergeFrom(
          from._internal_ack());
      break;
    }
    case kQuery: {
      _this->_internal_mutable_query()->::yoke::plugin::v1::Query::MergeFrom(
          from._internal_query());
      break;
    }
    case kData: {
      _this->_internal_mutable_data()->::yoke::plugin::v1::Data::MergeFrom(
          from._internal_data());
      break;
    }
    case kHealth: {
      _this->_internal_mutable_health()->::yoke::plugin::v1::Health::MergeFrom(
          from._internal_health());
      break;
    }
    case kEvent: {
      _this->_internal_mutable_event()->::yoke::plugin::v1::Event::MergeFrom(
          from._internal_event());
      break;
    }
    case kError: {
      _this->_internal_mutable_error()->::yoke::plugin::v1::Error::MergeFrom(
          from._internal_error());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:yoke.plugin.v1.Envelope)
}

inline void Envelope::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.message_id_){}
    , decltype(_impl_.session_id_){}
    , decltype(_impl_.correlation_id_){}
    , decltype(_impl_.sent_at_unix_nano_){int64_t{0}}
    , decltype(_impl_.payload_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  _impl_.message_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.session_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.session_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.correlation_id_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.correlation_id_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  clear_has_payload();
}

Envelope::~Envelope() {
  // @@protoc_insertion_point(destructor:yoke.plugin.v1.Envelope)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Envelope::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.message_id_.Destroy();
  _impl_.session_id_.Destroy();
  _impl_.correlation_id_.Destroy();
  if (has_payload()) {
    clear_payload();
  }
}

void Envelope::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Envelope::clear_payload() {
// @@protoc_insertion_point(one_of_clear_start:yoke.plugin.v1.Envelope)
  switch (payload_case()) {
    case kSession: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.session_;
      }
      break;
    }
    case kControl: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.control_;
      }
      break;
    }
    case kAck: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.ack_;
      }
      break;
    }
    case kQuery: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.query_;
      }
      break;
    }
    case kData: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.data_;
      }
      break;
    }
    case kHealth: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.health_;
      }
      break;
    }
    case kEvent: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.event_;
      }
      break;
    }
    case kError: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.payload_.error_;
      }
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PAYLOAD_NOT_SET;
}


void Envelope::Clear() {
// @@protoc_insertion_point(message_clear_start:yoke.plugin.v1.Envelope)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_id_.ClearToEmpty();
  _impl_.session_id_.ClearToEmpty();
  _impl_.correlation_id_.ClearToEmpty();
  _impl_.sent_at_unix_nano_ = int64_t{0};
  clear_payload();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Envelope::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string message_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_message_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "yoke.plugin.v1.Envelope.message_id"));
        } else
          goto handle_unusual;
        continue;
      // string session_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_session_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "yoke.plugin.v1.Envelope.session_id"));
        } else
          goto handle_unusual;
        continue;
      // int64 sent_at_unix_nano = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.sent_at_unix_nano_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string correlation_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_correlation_id();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "yoke.plugin.v1.Envelope.correlation_id"));
        } else
          goto handle_unusual;
        continue;
      // .yoke.plugin.v1.SessionMessage session = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_session(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .yoke.plugin.v1.Control control = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_control(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .yoke.plugin.v1.Ack ack = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr = ctx->ParseMessage(_internal_mutable_ack(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .yoke.plugin.v1.Query query = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 66)) {
          ptr = ctx->ParseMessage(_internal_mutable_query(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .yoke.plugin.v1.Data data = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 74)) {
          ptr = ctx->ParseMessage(_internal_mutable_data(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .yoke.plugin.v1.Health health = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 82)) {
          ptr = ctx->ParseMessage(_internal_mutable_health(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .yoke.plugin.v1.Event event = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 90)) {
          ptr = ctx->ParseMessage(_internal_mutable_event(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .yoke.plugin.v1.Error error = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 98)) {
          ptr = ctx->ParseMessage(_internal_mutable_error(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Envelope::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yoke.plugin.v1.Envelope)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string message_id = 1;
  if (!this->_internal_message_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message_id().data(), static_cast<int>(this->_internal_message_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yoke.plugin.v1.Envelope.message_id");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_message_id(), target);
  }

  // string session_id = 2;
  if (!this->_internal_session_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_session_id().data(), static_cast<int>(this->_internal_session_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yoke.plugin.v1.Envelope.session_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_session_id(), target);
  }

  // int64 sent_at_unix_nano = 3;
  if (this->_internal_sent_at_unix_nano() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt64ToArray(3, this->_internal_sent_at_unix_nano(), target);
  }

  // string correlation_id = 4;
  if (!this->_internal_correlation_id().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_correlation_id().data(), static_cast<int>(this->_internal_correlation_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yoke.plugin.v1.Envelope.correlation_id");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_correlation_id(), target);
  }

  // .yoke.plugin.v1.SessionMessage session = 5;
  if (_internal_has_session()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::session(this),
        _Internal::session(this).GetCachedSize(), target, stream);
  }

  // .yoke.plugin.v1.Control control = 6;
  if (_internal_has_control()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, _Internal::control(this),
        _Internal::control(this).GetCachedSize(), target, stream);
  }

  // .yoke.plugin.v1.Ack ack = 7;
  if (_internal_has_ack()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(7, _Internal::ack(this),
        _Internal::ack(this).GetCachedSize(), target, stream);
  }

  // .yoke.plugin.v1.Query query = 8;
  if (_internal_has_query()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(8, _Internal::query(this),
        _Internal::query(this).GetCachedSize(), target, stream);
  }

  // .yoke.plugin.v1.Data data = 9;
  if (_internal_has_data()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(9, _Internal::data(this),
        _Internal::data(this).GetCachedSize(), target, stream);
  }

  // .yoke.plugin.v1.Health health = 10;
  if (_internal_has_health()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(10, _Internal::health(this),
        _Internal::health(this).GetCachedSize(), target, stream);
  }

  // .yoke.plugin.v1.Event event = 11;
  if (_internal_has_event()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(11, _Internal::event(this),
        _Internal::event(this).GetCachedSize(), target, stream);
  }

  // .yoke.plugin.v1.Error error = 12;
  if (_internal_has_error()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(12, _Internal::error(this),
        _Internal::error(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yoke.plugin.v1.Envelope)
  return target;
}

size_t Envelope::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yoke.plugin.v1.Envelope)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message_id = 1;
  if (!this->_internal_message_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message_id());
  }

  // string session_id = 2;
  if (!this->_internal_session_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_session_id());
  }

  // string correlation_id = 4;
  if (!this->_internal_correlation_id().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_correlation_id());
  }

  // int64 sent_at_unix_nano = 3;
  if (this->_internal_sent_at_unix_nano() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this->_internal_sent_at_unix_nano());
  }

  switch (payload_case()) {
    // .yoke.plugin.v1.SessionMessage session = 5;
    case kSession: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.session_);
      break;
    }
    // .yoke.plugin.v1.Control control = 6;
    case kControl: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.control_);
      break;
    }
    // .yoke.plugin.v1.Ack ack = 7;
    case kAck: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.ack_);
      break;
    }
    // .yoke.plugin.v1.Query query = 8;
    case kQuery: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.query_);
      break;
    }
    // .yoke.plugin.v1.Data data = 9;
    case kData: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.data_);
      break;
    }
    // .yoke.plugin.v1.Health health = 10;
    case kHealth: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.health_);
      break;
    }
    // .yoke.plugin.v1.Event event = 11;
    case kEvent: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.event_);
      break;
    }
    // .yoke.plugin.v1.Error error = 12;
    case kError: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.payload_.error_);
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Envelope::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Envelope::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Envelope::GetClassData() const { return &_class_data_; }


void Envelope::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Envelope*>(&to_msg);
  auto& from = static_cast<const Envelope&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:yoke.plugin.v1.Envelope)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message_id().empty()) {
    _this->_internal_set_message_id(from._internal_message_id());
  }
  if (!from._internal_session_id().empty()) {
    _this->_internal_set_session_id(from._internal_session_id());
  }
  if (!from._internal_correlation_id().empty()) {
    _this->_internal_set_correlation_id(from._internal_correlation_id());
  }
  if (from._internal_sent_at_unix_nano() != 0) {
    _this->_internal_set_sent_at_unix_nano(from._internal_sent_at_unix_nano());
  }
  switch (from.payload_case()) {
    case kSession: {
      _this->_internal_mutable_session()->::yoke::plugin::v1::SessionMessage::MergeFrom(
          from._internal_session());
      break;
    }
    case kControl: {
      _this->_internal_mutable_control()->::yoke::plugin::v1::Control::MergeFrom(
          from._internal_control());
      break;
    }
    case kAck: {
      _this->_internal_mutable_ack()->::yoke::plugin::v1::Ack::MergeFrom(
          from._internal_ack());
      break;
    }
    case kQuery: {
      _this->_internal_mutable_query()->::yoke::plugin::v1::Query::MergeFrom(
          from._internal_query());
      break;
    }
    case kData: {
      _this->_internal_mutable_data()->::yoke::plugin::v1::Data::MergeFrom(
          from._internal_data());
      break;
    }
    case kHealth: {
      _this->_internal_mutable_health()->::yoke::plugin::v1::Health::MergeFrom(
          from._internal_health());
      break;
    }
    case kEvent: {
      _this->_internal_mutable_event()->::yoke::plugin::v1::Event::MergeFrom(
          from._internal_event());
      break;
    }
    case kError: {
      _this->_internal_mutable_error()->::yoke::plugin::v1::Error::MergeFrom(
          from._internal_error());
      break;
    }
    case PAYLOAD_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Envelope::CopyFrom(const Envelope& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yoke.plugin.v1.Envelope)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Envelope::IsInitialized() const {
  return true;
}

void Envelope::InternalSwap(Envelope* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_id_, lhs_arena,
      &other->_impl_.message_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.session_id_, lhs_arena,
      &other->_impl_.session_id_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.correlation_id_, lhs_arena,
      &other->_impl_.correlation_id_, rhs_arena
  );
  swap(_impl_.sent_at_unix_nano_, other->_impl_.sent_at_unix_nano_);
  swap(_impl_.payload_, other->_impl_.payload_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata Envelope::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_yoke_2fplugin_2fv1_2fsession_2eproto_getter, &descriptor_table_yoke_2fplugin_2fv1_2fsession_2eproto_once,
      file_level_metadata_yoke_2fplugin_2fv1_2fsession_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace plugin
}  // namespace yoke
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::yoke::plugin::v1::Envelope*
Arena::CreateMaybeMessage< ::yoke::plugin::v1::Envelope >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yoke::plugin::v1::Envelope >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
