// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: yoke/administrative/v1/operator.proto
// Original file comments:
// The operator projection, on operator.sock: a call and its answer, or one call answered by a stream.
#ifndef GRPC_yoke_2fadministrative_2fv1_2foperator_2eproto__INCLUDED
#define GRPC_yoke_2fadministrative_2fv1_2foperator_2eproto__INCLUDED

#include "yoke/administrative/v1/operator.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace yoke {
namespace administrative {
namespace v1 {

class Operator final {
 public:
  static constexpr char const* service_full_name() {
    return "yoke.administrative.v1.Operator";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // One operation, one answer. A refusal travels in the status, carrying the structured Refusal.
    virtual ::grpc::Status Call(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request& request, ::yoke::administrative::v1::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::yoke::administrative::v1::Response>> AsyncCall(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::yoke::administrative::v1::Response>>(AsyncCallRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::yoke::administrative::v1::Response>> PrepareAsyncCall(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::yoke::administrative::v1::Response>>(PrepareAsyncCallRaw(context, request, cq));
    }
    // One operation whose answer is a stream: subscribe, and log.follow.
    std::unique_ptr< ::grpc::ClientReaderInterface< ::yoke::administrative::v1::Response>> Watch(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::yoke::administrative::v1::Response>>(WatchRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::yoke::administrative::v1::Response>> AsyncWatch(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::yoke::administrative::v1::Response>>(AsyncWatchRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::yoke::administrative::v1::Response>> PrepareAsyncWatch(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::yoke::administrative::v1::Response>>(PrepareAsyncWatchRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // One operation, one answer. A refusal travels in the status, carrying the structured Refusal.
      virtual void Call(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request* request, ::yoke::administrative::v1::Response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Call(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request* request, ::yoke::administrative::v1::Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // One operation whose answer is a stream: subscribe, and log.follow.
      virtual void Watch(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request* request, ::grpc::ClientReadReactor< ::yoke::administrative::v1::Response>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::yoke::administrative::v1::Response>* AsyncCallRaw(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::yoke::administrative::v1::Response>* PrepareAsyncCallRaw(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderInterface< ::yoke::administrative::v1::Response>* WatchRaw(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::yoke::administrative::v1::Response>* AsyncWatchRaw(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::yoke::administrative::v1::Response>* PrepareAsyncWatchRaw(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Call(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request& request, ::yoke::administrative::v1::Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::yoke::administrative::v1::Response>> AsyncCall(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::yoke::administrative::v1::Response>>(AsyncCallRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::yoke::administrative::v1::Response>> PrepareAsyncCall(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::yoke::administrative::v1::Response>>(PrepareAsyncCallRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientReader< ::yoke::administrative::v1::Response>> Watch(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::yoke::administrative::v1::Response>>(WatchRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::yoke::administrative::v1::Response>> AsyncWatch(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::yoke::administrative::v1::Response>>(AsyncWatchRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::yoke::administrative::v1::Response>> PrepareAsyncWatch(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::yoke::administrative::v1::Response>>(PrepareAsyncWatchRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Call(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request* request, ::yoke::administrative::v1::Response* response, std::function<void(::grpc::Status)>) override;
      void Call(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request* request, ::yoke::administrative::v1::Response* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Watch(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request* request, ::grpc::ClientReadReactor< ::yoke::administrative::v1::Response>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::yoke::administrative::v1::Response>* AsyncCallRaw(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::yoke::administrative::v1::Response>* PrepareAsyncCallRaw(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReader< ::yoke::administrative::v1::Response>* WatchRaw(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request& request) override;
    ::grpc::ClientAsyncReader< ::yoke::administrative::v1::Response>* AsyncWatchRaw(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::yoke::administrative::v1::Response>* PrepareAsyncWatchRaw(::grpc::ClientContext* context, const ::yoke::administrative::v1::Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Call_;
    const ::grpc::internal::RpcMethod rpcmethod_Watch_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // One operation, one answer. A refusal travels in the status, carrying the structured Refusal.
    virtual ::grpc::Status Call(::grpc::ServerContext* context, const ::yoke::administrative::v1::Request* request, ::yoke::administrative::v1::Response* response);
    // One operation whose answer is a stream: subscribe, and log.follow.
    virtual ::grpc::Status Watch(::grpc::ServerContext* context, const ::yoke::administrative::v1::Request* request, ::grpc::ServerWriter< ::yoke::administrative::v1::Response>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_Call : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Call() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Call() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Call(::grpc::ServerContext* /*context*/, const ::yoke::administrative::v1::Request* /*request*/, ::yoke::administrative::v1::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCall(::grpc::ServerContext* context, ::yoke::administrative::v1::Request* request, ::grpc::ServerAsyncResponseWriter< ::yoke::administrative::v1::Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Watch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Watch() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Watch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Watch(::grpc::ServerContext* /*context*/, const ::yoke::administrative::v1::Request* /*request*/, ::grpc::ServerWriter< ::yoke::administrative::v1::Response>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestWatch(::grpc::ServerContext* context, ::yoke::administrative::v1::Request* request, ::grpc::ServerAsyncWriter< ::yoke::administrative::v1::Response>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Call<WithAsyncMethod_Watch<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Call : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Call() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::yoke::administrative::v1::Request, ::yoke::administrative::v1::Response>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::yoke::administrative::v1::Request* request, ::yoke::administrative::v1::Response* response) { return this->Call(context, request, response); }));}
    void SetMessageAllocatorFor_Call(
        ::grpc::MessageAllocator< ::yoke::administrative::v1::Request, ::yoke::administrative::v1::Response>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::yoke::administrative::v1::Request, ::yoke::administrative::v1::Response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Call() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Call(::grpc::ServerContext* /*context*/, const ::yoke::administrative::v1::Request* /*request*/, ::yoke::administrative::v1::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Call(
      ::grpc::CallbackServerContext* /*context*/, const ::yoke::administrative::v1::Request* /*request*/, ::yoke::administrative::v1::Response* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Watch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Watch() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::yoke::administrative::v1::Request, ::yoke::administrative::v1::Response>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::yoke::administrative::v1::Request* request) { return this->Watch(context, request); }));
    }
    ~WithCallbackMethod_Watch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Watch(::grpc::ServerContext* /*context*/, const ::yoke::administrative::v1::Request* /*request*/, ::grpc::ServerWriter< ::yoke::administrative::v1::Response>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::yoke::administrative::v1::Response>* Watch(
      ::grpc::CallbackServerContext* /*context*/, const ::yoke::administrative::v1::Request* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Call<WithCallbackMethod_Watch<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Call : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Call() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Call() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Call(::grpc::ServerContext* /*context*/, const ::yoke::administrative::v1::Request* /*request*/, ::yoke::administrative::v1::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Watch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Watch() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Watch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Watch(::grpc::ServerContext* /*context*/, const ::yoke::administrative::v1::Request* /*request*/, ::grpc::ServerWriter< ::yoke::administrative::v1::Response>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Call : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Call() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Call() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Call(::grpc::ServerContext* /*context*/, const ::yoke::administrative::v1::Request* /*request*/, ::yoke::administrative::v1::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCall(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Watch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Watch() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Watch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Watch(::grpc::ServerContext* /*context*/, const ::yoke::administrative::v1::Request* /*request*/, ::grpc::ServerWriter< ::yoke::administrative::v1::Response>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestWatch(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(1, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Call : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Call() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Call(context, request, response); }));
    }
    ~WithRawCallbackMethod_Call() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Call(::grpc::ServerContext* /*context*/, const ::yoke::administrative::v1::Request* /*request*/, ::yoke::administrative::v1::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Call(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Watch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Watch() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->Watch(context, request); }));
    }
    ~WithRawCallbackMethod_Watch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Watch(::grpc::ServerContext* /*context*/, const ::yoke::administrative::v1::Request* /*request*/, ::grpc::ServerWriter< ::yoke::administrative::v1::Response>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* Watch(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Call : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Call() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::yoke::administrative::v1::Request, ::yoke::administrative::v1::Response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::yoke::administrative::v1::Request, ::yoke::administrative::v1::Response>* streamer) {
                       return this->StreamedCall(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Call() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Call(::grpc::ServerContext* /*context*/, const ::yoke::administrative::v1::Request* /*request*/, ::yoke::administrative::v1::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCall(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::yoke::administrative::v1::Request,::yoke::administrative::v1::Response>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Call<Service > StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_Watch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_Watch() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::yoke::administrative::v1::Request, ::yoke::administrative::v1::Response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::yoke::administrative::v1::Request, ::yoke::administrative::v1::Response>* streamer) {
                       return this->StreamedWatch(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_Watch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Watch(::grpc::ServerContext* /*context*/, const ::yoke::administrative::v1::Request* /*request*/, ::grpc::ServerWriter< ::yoke::administrative::v1::Response>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedWatch(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::yoke::administrative::v1::Request,::yoke::administrative::v1::Response>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_Watch<Service > SplitStreamedService;
  typedef WithStreamedUnaryMethod_Call<WithSplitStreamingMethod_Watch<Service > > StreamedService;
};

}  // namespace v1
}  // namespace administrative
}  // namespace yoke


#endif  // GRPC_yoke_2fadministrative_2fv1_2foperator_2eproto__INCLUDED
