// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yoke/administrative/v1/operator.proto

#include "yoke/administrative/v1/operator.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace yoke {
namespace administrative {
namespace v1 {
}  // namespace v1
}  // namespace administrative
}  // namespace yoke
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_yoke_2fadministrative_2fv1_2foperator_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_yoke_2fadministrative_2fv1_2foperator_2eproto = nullptr;
const uint32_t TableStruct_yoke_2fadministrative_2fv1_2foperator_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_yoke_2fadministrative_2fv1_2foperator_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n%yoke/administrative/v1/operator.proto\022"
  "\026yoke.administrative.v1\032\'yoke/administra"
  "tive/v1/operations.proto2\243\001\n\010Operator\022I\n"
  "\004Call\022\037.yoke.administrative.v1.Request\032 "
  ".yoke.administrative.v1.Response\022L\n\005Watc"
  "h\022\037.yoke.administrative.v1.Request\032 .yok"
  "e.administrative.v1.Response0\001BLZJgithub"
  ".com/yoke-project/yoke/proto/yoke/admini"
  "strative/v1;administrativev1b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_yoke_2fadministrative_2fv1_2foperator_2eproto_deps[1] = {
  &::descriptor_table_yoke_2fadministrative_2fv1_2foperations_2eproto,
};
static ::_pbi::once_flag descriptor_table_yoke_2fadministrative_2fv1_2foperator_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_yoke_2fadministrative_2fv1_2foperator_2eproto = {
    false, false, 356, descriptor_table_protodef_yoke_2fadministrative_2fv1_2foperator_2eproto,
    "yoke/administrative/v1/operator.proto",
    &descriptor_table_yoke_2fadministrative_2fv1_2foperator_2eproto_once, descriptor_table_yoke_2fadministrative_2fv1_2foperator_2eproto_deps, 1, 0,
    schemas, file_default_instances, TableStruct_yoke_2fadministrative_2fv1_2foperator_2eproto::offsets,
    nullptr, file_level_enum_descriptors_yoke_2fadministrative_2fv1_2foperator_2eproto,
    file_level_service_descriptors_yoke_2fadministrative_2fv1_2foperator_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_yoke_2fadministrative_2fv1_2foperator_2eproto_getter() {
  return &descriptor_table_yoke_2fadministrative_2fv1_2foperator_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_yoke_2fadministrative_2fv1_2foperator_2eproto(&descriptor_table_yoke_2fadministrative_2fv1_2foperator_2eproto);
namespace yoke {
namespace administrative {
namespace v1 {

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace administrative
}  // namespace yoke
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
