// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yoke/interface/v1/codes.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_yoke_2finterface_2fv1_2fcodes_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_yoke_2finterface_2fv1_2fcodes_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/descriptor.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_yoke_2finterface_2fv1_2fcodes_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_yoke_2finterface_2fv1_2fcodes_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_yoke_2finterface_2fv1_2fcodes_2eproto;
namespace yoke {
namespace interface {
namespace v1 {
class Refusal;
struct RefusalDefaultTypeInternal;
extern RefusalDefaultTypeInternal _Refusal_default_instance_;
class Subject;
struct SubjectDefaultTypeInternal;
extern SubjectDefaultTypeInternal _Subject_default_instance_;
class Suspension;
struct SuspensionDefaultTypeInternal;
extern SuspensionDefaultTypeInternal _Suspension_default_instance_;
}  // namespace v1
}  // namespace interface
}  // namespace yoke
PROTOBUF_NAMESPACE_OPEN
template<> ::yoke::interface::v1::Refusal* Arena::CreateMaybeMessage<::yoke::interface::v1::Refusal>(Arena*);
template<> ::yoke::interface::v1::Subject* Arena::CreateMaybeMessage<::yoke::interface::v1::Subject>(Arena*);
template<> ::yoke::interface::v1::Suspension* Arena::CreateMaybeMessage<::yoke::interface::v1::Suspension>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace yoke {
namespace interface {
namespace v1 {

enum Code : int {
  CODE_UNSPECIFIED = 0,
  CODE_OPERATION_MALFORMED = 1,
  CODE_OPERATION_UNKNOWN = 2,
  CODE_COMPAT_UNSUPPORTED = 3,
  CODE_AUTH_REQUIRED = 4,
  CODE_AUTH_INVALID = 5,
  CODE_CHANNEL_IN_USE = 6,
  CODE_CHANNEL_NOT_ATTACHED = 7,
  CODE_CHANNEL_SUSPENDED = 8,
  CODE_CHANNEL_NOT_LOCAL = 9,
  CODE_SUBJECT_UNKNOWN = 10,
  CODE_SCOPE_UNDECLARED = 11,
  CODE_SCOPE_WITHHELD = 12,
  CODE_UNIT_NOT_RUNNING = 13,
  CODE_UNIT_NO_SESSION = 14,
  CODE_UNIT_UNANSWERED = 15,
  CODE_INSTANCE_STOPPING = 16,
  CODE_UNIT_FAILED = 17,
  Code_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Code_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Code_IsValid(int value);
constexpr Code Code_MIN = CODE_UNSPECIFIED;
constexpr Code Code_MAX = CODE_UNIT_FAILED;
constexpr int Code_ARRAYSIZE = Code_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Code_descriptor();
template<typename T>
inline const std::string& Code_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Code>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Code_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Code_descriptor(), enum_t_value);
}
inline bool Code_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Code* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Code>(
    Code_descriptor(), name, value);
}
// ===================================================================

class Refusal final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yoke.interface.v1.Refusal) */ {
 public:
  inline Refusal() : Refusal(nullptr) {}
  ~Refusal() override;
  explicit PROTOBUF_CONSTEXPR Refusal(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Refusal(const Refusal& from);
  Refusal(Refusal&& from) noexcept
    : Refusal() {
    *this = ::std::move(from);
  }

  inline Refusal& operator=(const Refusal& from) {
    CopyFrom(from);
    return *this;
  }
  inline Refusal& operator=(Refusal&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Refusal& default_instance() {
    return *internal_default_instance();
  }
  enum DetailCase {
    kSubject = 3,
    kItem = 4,
    kSuspension = 5,
    DETAIL_NOT_SET = 0,
  };

  static inline const Refusal* internal_default_instance() {
    return reinterpret_cast<const Refusal*>(
               &_Refusal_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Refusal& a, Refusal& b) {
    a.Swap(&b);
  }
  inline void Swap(Refusal* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Refusal* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Refusal* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Refusal>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Refusal& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Refusal& from) {
    Refusal::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Refusal* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yoke.interface.v1.Refusal";
  }
  protected:
  explicit Refusal(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCodeFieldNumber = 1,
    kMessageFieldNumber = 2,
    kSubjectFieldNumber = 3,
    kItemFieldNumber = 4,
    kSuspensionFieldNumber = 5,
  };
  // string code = 1;
  void clear_code();
  const std::string& code() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_code(ArgT0&& arg0, ArgT... args);
  std::string* mutable_code();
  PROTOBUF_NODISCARD std::string* release_code();
  void set_allocated_code(std::string* code);
  private:
  const std::string& _internal_code() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_code(const std::string& value);
  std::string* _internal_mutable_code();
  public:

  // string message = 2;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // .yoke.interface.v1.Subject subject = 3;
  bool has_subject() const;
  private:
  bool _internal_has_subject() const;
  public:
  void clear_subject();
  const ::yoke::interface::v1::Subject& subject() const;
  PROTOBUF_NODISCARD ::yoke::interface::v1::Subject* release_subject();
  ::yoke::interface::v1::Subject* mutable_subject();
  void set_allocated_subject(::yoke::interface::v1::Subject* subject);
  private:
  const ::yoke::interface::v1::Subject& _internal_subject() const;
  ::yoke::interface::v1::Subject* _internal_mutable_subject();
  public:
  void unsafe_arena_set_allocated_subject(
      ::yoke::interface::v1::Subject* subject);
  ::yoke::interface::v1::Subject* unsafe_arena_release_subject();

  // string item = 4;
  bool has_item() const;
  private:
  bool _internal_has_item() const;
  public:
  void clear_item();
  const std::string& item() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_item(ArgT0&& arg0, ArgT... args);
  std::string* mutable_item();
  PROTOBUF_NODISCARD std::string* release_item();
  void set_allocated_item(std::string* item);
  private:
  const std::string& _internal_item() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_item(const std::string& value);
  std::string* _internal_mutable_item();
  public:

  // .yoke.interface.v1.Suspension suspension = 5;
  bool has_suspension() const;
  private:
  bool _internal_has_suspension() const;
  public:
  void clear_suspension();
  const ::yoke::interface::v1::Suspension& suspension() const;
  PROTOBUF_NODISCARD ::yoke::interface::v1::Suspension* release_suspension();
  ::yoke::interface::v1::Suspension* mutable_suspension();
  void set_allocated_suspension(::yoke::interface::v1::Suspension* suspension);
  private:
  const ::yoke::interface::v1::Suspension& _internal_suspension() const;
  ::yoke::interface::v1::Suspension* _internal_mutable_suspension();
  public:
  void unsafe_arena_set_allocated_suspension(
      ::yoke::interface::v1::Suspension* suspension);
  ::yoke::interface::v1::Suspension* unsafe_arena_release_suspension();

  void clear_detail();
  DetailCase detail_case() const;
  // @@protoc_insertion_point(class_scope:yoke.interface.v1.Refusal)
 private:
  class _Internal;
  void set_has_subject();
  void set_has_item();
  void set_has_suspension();

  inline bool has_detail() const;
  inline void clear_has_detail();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr code_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    union DetailUnion {
      constexpr DetailUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::yoke::interface::v1::Subject* subject_;
      ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr item_;
      ::yoke::interface::v1::Suspension* suspension_;
    } detail_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_yoke_2finterface_2fv1_2fcodes_2eproto;
};
// -------------------------------------------------------------------

class Subject final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yoke.interface.v1.Subject) */ {
 public:
  inline Subject() : Subject(nullptr) {}
  ~Subject() override;
  explicit PROTOBUF_CONSTEXPR Subject(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Subject(const Subject& from);
  Subject(Subject&& from) noexcept
    : Subject() {
    *this = ::std::move(from);
  }

  inline Subject& operator=(const Subject& from) {
    CopyFrom(from);
    return *this;
  }
  inline Subject& operator=(Subject&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Subject& default_instance() {
    return *internal_default_instance();
  }
  static inline const Subject* internal_default_instance() {
    return reinterpret_cast<const Subject*>(
               &_Subject_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Subject& a, Subject& b) {
    a.Swap(&b);
  }
  inline void Swap(Subject* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Subject* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Subject* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Subject>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Subject& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Subject& from) {
    Subject::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Subject* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yoke.interface.v1.Subject";
  }
  protected:
  explicit Subject(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKindFieldNumber = 1,
    kIdentityFieldNumber = 2,
    kIncarnationFieldNumber = 3,
  };
  // string kind = 1;
  void clear_kind();
  const std::string& kind() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_kind(ArgT0&& arg0, ArgT... args);
  std::string* mutable_kind();
  PROTOBUF_NODISCARD std::string* release_kind();
  void set_allocated_kind(std::string* kind);
  private:
  const std::string& _internal_kind() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_kind(const std::string& value);
  std::string* _internal_mutable_kind();
  public:

  // string identity = 2;
  void clear_identity();
  const std::string& identity() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_identity(ArgT0&& arg0, ArgT... args);
  std::string* mutable_identity();
  PROTOBUF_NODISCARD std::string* release_identity();
  void set_allocated_identity(std::string* identity);
  private:
  const std::string& _internal_identity() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_identity(const std::string& value);
  std::string* _internal_mutable_identity();
  public:

  // uint64 incarnation = 3;
  void clear_incarnation();
  uint64_t incarnation() const;
  void set_incarnation(uint64_t value);
  private:
  uint64_t _internal_incarnation() const;
  void _internal_set_incarnation(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:yoke.interface.v1.Subject)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr kind_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr identity_;
    uint64_t incarnation_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_yoke_2finterface_2fv1_2fcodes_2eproto;
};
// -------------------------------------------------------------------

class Suspension final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yoke.interface.v1.Suspension) */ {
 public:
  inline Suspension() : Suspension(nullptr) {}
  ~Suspension() override;
  explicit PROTOBUF_CONSTEXPR Suspension(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Suspension(const Suspension& from);
  Suspension(Suspension&& from) noexcept
    : Suspension() {
    *this = ::std::move(from);
  }

  inline Suspension& operator=(const Suspension& from) {
    CopyFrom(from);
    return *this;
  }
  inline Suspension& operator=(Suspension&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Suspension& default_instance() {
    return *internal_default_instance();
  }
  static inline const Suspension* internal_default_instance() {
    return reinterpret_cast<const Suspension*>(
               &_Suspension_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Suspension& a, Suspension& b) {
    a.Swap(&b);
  }
  inline void Swap(Suspension* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Suspension* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Suspension* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Suspension>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Suspension& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Suspension& from) {
    Suspension::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Suspension* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yoke.interface.v1.Suspension";
  }
  protected:
  explicit Suspension(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kGradeFieldNumber = 1,
    kByFieldNumber = 2,
  };
  // string grade = 1;
  void clear_grade();
  const std::string& grade() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_grade(ArgT0&& arg0, ArgT... args);
  std::string* mutable_grade();
  PROTOBUF_NODISCARD std::string* release_grade();
  void set_allocated_grade(std::string* grade);
  private:
  const std::string& _internal_grade() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_grade(const std::string& value);
  std::string* _internal_mutable_grade();
  public:

  // string by = 2;
  void clear_by();
  const std::string& by() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_by(ArgT0&& arg0, ArgT... args);
  std::string* mutable_by();
  PROTOBUF_NODISCARD std::string* release_by();
  void set_allocated_by(std::string* by);
  private:
  const std::string& _internal_by() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_by(const std::string& value);
  std::string* _internal_mutable_by();
  public:

  // @@protoc_insertion_point(class_scope:yoke.interface.v1.Suspension)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr grade_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr by_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_yoke_2finterface_2fv1_2fcodes_2eproto;
};
// ===================================================================

static const int kCodeFieldNumber = 50002;
extern ::PROTOBUF_NAMESPACE_ID::internal::ExtensionIdentifier< ::PROTOBUF_NAMESPACE_ID::EnumValueOptions,
    ::PROTOBUF_NAMESPACE_ID::internal::StringTypeTraits, 9, false >
  code;

// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Refusal

// string code = 1;
inline void Refusal::clear_code() {
  _impl_.code_.ClearToEmpty();
}
inline const std::string& Refusal::code() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.Refusal.code)
  return _internal_code();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Refusal::set_code(ArgT0&& arg0, ArgT... args) {
 
 _impl_.code_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:yoke.interface.v1.Refusal.code)
}
inline std::string* Refusal::mutable_code() {
  std::string* _s = _internal_mutable_code();
  // @@protoc_insertion_point(field_mutable:yoke.interface.v1.Refusal.code)
  return _s;
}
inline const std::string& Refusal::_internal_code() const {
  return _impl_.code_.Get();
}
inline void Refusal::_internal_set_code(const std::string& value) {
  
  _impl_.code_.Set(value, GetArenaForAllocation());
}
inline std::string* Refusal::_internal_mutable_code() {
  
  return _impl_.code_.Mutable(GetArenaForAllocation());
}
inline std::string* Refusal::release_code() {
  // @@protoc_insertion_point(field_release:yoke.interface.v1.Refusal.code)
  return _impl_.code_.Release();
}
inline void Refusal::set_allocated_code(std::string* code) {
  if (code != nullptr) {
    
  } else {
    
  }
  _impl_.code_.SetAllocated(code, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.code_.IsDefault()) {
    _impl_.code_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:yoke.interface.v1.Refusal.code)
}

// string message = 2;
inline void Refusal::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& Refusal::message() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.Refusal.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Refusal::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:yoke.interface.v1.Refusal.message)
}
inline std::string* Refusal::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:yoke.interface.v1.Refusal.message)
  return _s;
}
inline const std::string& Refusal::_internal_message() const {
  return _impl_.message_.Get();
}
inline void Refusal::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* Refusal::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* Refusal::release_message() {
  // @@protoc_insertion_point(field_release:yoke.interface.v1.Refusal.message)
  return _impl_.message_.Release();
}
inline void Refusal::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:yoke.interface.v1.Refusal.message)
}

// .yoke.interface.v1.Subject subject = 3;
inline bool Refusal::_internal_has_subject() const {
  return detail_case() == kSubject;
}
inline bool Refusal::has_subject() const {
  return _internal_has_subject();
}
inline void Refusal::set_has_subject() {
  _impl_._oneof_case_[0] = kSubject;
}
inline void Refusal::clear_subject() {
  if (_internal_has_subject()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.detail_.subject_;
    }
    clear_has_detail();
  }
}
inline ::yoke::interface::v1::Subject* Refusal::release_subject() {
  // @@protoc_insertion_point(field_release:yoke.interface.v1.Refusal.subject)
  if (_internal_has_subject()) {
    clear_has_detail();
    ::yoke::interface::v1::Subject* temp = _impl_.detail_.subject_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.detail_.subject_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::yoke::interface::v1::Subject& Refusal::_internal_subject() const {
  return _internal_has_subject()
      ? *_impl_.detail_.subject_
      : reinterpret_cast< ::yoke::interface::v1::Subject&>(::yoke::interface::v1::_Subject_default_instance_);
}
inline const ::yoke::interface::v1::Subject& Refusal::subject() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.Refusal.subject)
  return _internal_subject();
}
inline ::yoke::interface::v1::Subject* Refusal::unsafe_arena_release_subject() {
  // @@protoc_insertion_point(field_unsafe_arena_release:yoke.interface.v1.Refusal.subject)
  if (_internal_has_subject()) {
    clear_has_detail();
    ::yoke::interface::v1::Subject* temp = _impl_.detail_.subject_;
    _impl_.detail_.subject_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Refusal::unsafe_arena_set_allocated_subject(::yoke::interface::v1::Subject* subject) {
  clear_detail();
  if (subject) {
    set_has_subject();
    _impl_.detail_.subject_ = subject;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:yoke.interface.v1.Refusal.subject)
}
inline ::yoke::interface::v1::Subject* Refusal::_internal_mutable_subject() {
  if (!_internal_has_subject()) {
    clear_detail();
    set_has_subject();
    _impl_.detail_.subject_ = CreateMaybeMessage< ::yoke::interface::v1::Subject >(GetArenaForAllocation());
  }
  return _impl_.detail_.subject_;
}
inline ::yoke::interface::v1::Subject* Refusal::mutable_subject() {
  ::yoke::interface::v1::Subject* _msg = _internal_mutable_subject();
  // @@protoc_insertion_point(field_mutable:yoke.interface.v1.Refusal.subject)
  return _msg;
}

// string item = 4;
inline bool Refusal::_internal_has_item() const {
  return detail_case() == kItem;
}
inline bool Refusal::has_item() const {
  return _internal_has_item();
}
inline void Refusal::set_has_item() {
  _impl_._oneof_case_[0] = kItem;
}
inline void Refusal::clear_item() {
  if (_internal_has_item()) {
    _impl_.detail_.item_.Destroy();
    clear_has_detail();
  }
}
inline const std::string& Refusal::item() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.Refusal.item)
  return _internal_item();
}
template <typename ArgT0, typename... ArgT>
inline void Refusal::set_item(ArgT0&& arg0, ArgT... args) {
  if (!_internal_has_item()) {
    clear_detail();
    set_has_item();
    _impl_.detail_.item_.InitDefault();
  }
  _impl_.detail_.item_.Set( static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:yoke.interface.v1.Refusal.item)
}
inline std::string* Refusal::mutable_item() {
  std::string* _s = _internal_mutable_item();
  // @@protoc_insertion_point(field_mutable:yoke.interface.v1.Refusal.item)
  return _s;
}
inline const std::string& Refusal::_internal_item() const {
  if (_internal_has_item()) {
    return _impl_.detail_.item_.Get();
  }
  return ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited();
}
inline void Refusal::_internal_set_item(const std::string& value) {
  if (!_internal_has_item()) {
    clear_detail();
    set_has_item();
    _impl_.detail_.item_.InitDefault();
  }
  _impl_.detail_.item_.Set(value, GetArenaForAllocation());
}
inline std::string* Refusal::_internal_mutable_item() {
  if (!_internal_has_item()) {
    clear_detail();
    set_has_item();
    _impl_.detail_.item_.InitDefault();
  }
  return _impl_.detail_.item_.Mutable(      GetArenaForAllocation());
}
inline std::string* Refusal::release_item() {
  // @@protoc_insertion_point(field_release:yoke.interface.v1.Refusal.item)
  if (_internal_has_item()) {
    clear_has_detail();
    return _impl_.detail_.item_.Release();
  } else {
    return nullptr;
  }
}
inline void Refusal::set_allocated_item(std::string* item) {
  if (has_detail()) {
    clear_detail();
  }
  if (item != nullptr) {
    set_has_item();
    _impl_.detail_.item_.InitAllocated(item, GetArenaForAllocation());
  }
  // @@protoc_insertion_point(field_set_allocated:yoke.interface.v1.Refusal.item)
}

// .yoke.interface.v1.Suspension suspension = 5;
inline bool Refusal::_internal_has_suspension() const {
  return detail_case() == kSuspension;
}
inline bool Refusal::has_suspension() const {
  return _internal_has_suspension();
}
inline void Refusal::set_has_suspension() {
  _impl_._oneof_case_[0] = kSuspension;
}
inline void Refusal::clear_suspension() {
  if (_internal_has_suspension()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.detail_.suspension_;
    }
    clear_has_detail();
  }
}
inline ::yoke::interface::v1::Suspension* Refusal::release_suspension() {
  // @@protoc_insertion_point(field_release:yoke.interface.v1.Refusal.suspension)
  if (_internal_has_suspension()) {
    clear_has_detail();
    ::yoke::interface::v1::Suspension* temp = _impl_.detail_.suspension_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.detail_.suspension_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::yoke::interface::v1::Suspension& Refusal::_internal_suspension() const {
  return _internal_has_suspension()
      ? *_impl_.detail_.suspension_
      : reinterpret_cast< ::yoke::interface::v1::Suspension&>(::yoke::interface::v1::_Suspension_default_instance_);
}
inline const ::yoke::interface::v1::Suspension& Refusal::suspension() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.Refusal.suspension)
  return _internal_suspension();
}
inline ::yoke::interface::v1::Suspension* Refusal::unsafe_arena_release_suspension() {
  // @@protoc_insertion_point(field_unsafe_arena_release:yoke.interface.v1.Refusal.suspension)
  if (_internal_has_suspension()) {
    clear_has_detail();
    ::yoke::interface::v1::Suspension* temp = _impl_.detail_.suspension_;
    _impl_.detail_.suspension_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Refusal::unsafe_arena_set_allocated_suspension(::yoke::interface::v1::Suspension* suspension) {
  clear_detail();
  if (suspension) {
    set_has_suspension();
    _impl_.detail_.suspension_ = suspension;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:yoke.interface.v1.Refusal.suspension)
}
inline ::yoke::interface::v1::Suspension* Refusal::_internal_mutable_suspension() {
  if (!_internal_has_suspension()) {
    clear_detail();
    set_has_suspension();
    _impl_.detail_.suspension_ = CreateMaybeMessage< ::yoke::interface::v1::Suspension >(GetArenaForAllocation());
  }
  return _impl_.detail_.suspension_;
}
inline ::yoke::interface::v1::Suspension* Refusal::mutable_suspension() {
  ::yoke::interface::v1::Suspension* _msg = _internal_mutable_suspension();
  // @@protoc_insertion_point(field_mutable:yoke.interface.v1.Refusal.suspension)
  return _msg;
}

inline bool Refusal::has_detail() const {
  return detail_case() != DETAIL_NOT_SET;
}
inline void Refusal::clear_has_detail() {
  _impl_._oneof_case_[0] = DETAIL_NOT_SET;
}
inline Refusal::DetailCase Refusal::detail_case() const {
  return Refusal::DetailCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// Subject

// string kind = 1;
inline void Subject::clear_kind() {
  _impl_.kind_.ClearToEmpty();
}
inline const std::string& Subject::kind() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.Subject.kind)
  return _internal_kind();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Subject::set_kind(ArgT0&& arg0, ArgT... args) {
 
 _impl_.kind_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:yoke.interface.v1.Subject.kind)
}
inline std::string* Subject::mutable_kind() {
  std::string* _s = _internal_mutable_kind();
  // @@protoc_insertion_point(field_mutable:yoke.interface.v1.Subject.kind)
  return _s;
}
inline const std::string& Subject::_internal_kind() const {
  return _impl_.kind_.Get();
}
inline void Subject::_internal_set_kind(const std::string& value) {
  
  _impl_.kind_.Set(value, GetArenaForAllocation());
}
inline std::string* Subject::_internal_mutable_kind() {
  
  return _impl_.kind_.Mutable(GetArenaForAllocation());
}
inline std::string* Subject::release_kind() {
  // @@protoc_insertion_point(field_release:yoke.interface.v1.Subject.kind)
  return _impl_.kind_.Release();
}
inline void Subject::set_allocated_kind(std::string* kind) {
  if (kind != nullptr) {
    
  } else {
    
  }
  _impl_.kind_.SetAllocated(kind, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.kind_.IsDefault()) {
    _impl_.kind_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:yoke.interface.v1.Subject.kind)
}

// string identity = 2;
inline void Subject::clear_identity() {
  _impl_.identity_.ClearToEmpty();
}
inline const std::string& Subject::identity() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.Subject.identity)
  return _internal_identity();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Subject::set_identity(ArgT0&& arg0, ArgT... args) {
 
 _impl_.identity_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:yoke.interface.v1.Subject.identity)
}
inline std::string* Subject::mutable_identity() {
  std::string* _s = _internal_mutable_identity();
  // @@protoc_insertion_point(field_mutable:yoke.interface.v1.Subject.identity)
  return _s;
}
inline const std::string& Subject::_internal_identity() const {
  return _impl_.identity_.Get();
}
inline void Subject::_internal_set_identity(const std::string& value) {
  
  _impl_.identity_.Set(value, GetArenaForAllocation());
}
inline std::string* Subject::_internal_mutable_identity() {
  
  return _impl_.identity_.Mutable(GetArenaForAllocation());
}
inline std::string* Subject::release_identity() {
  // @@protoc_insertion_point(field_release:yoke.interface.v1.Subject.identity)
  return _impl_.identity_.Release();
}
inline void Subject::set_allocated_identity(std::string* identity) {
  if (identity != nullptr) {
    
  } else {
    
  }
  _impl_.identity_.SetAllocated(identity, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.identity_.IsDefault()) {
    _impl_.identity_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:yoke.interface.v1.Subject.identity)
}

// uint64 incarnation = 3;
inline void Subject::clear_incarnation() {
  _impl_.incarnation_ = uint64_t{0u};
}
inline uint64_t Subject::_internal_incarnation() const {
  return _impl_.incarnation_;
}
inline uint64_t Subject::incarnation() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.Subject.incarnation)
  return _internal_incarnation();
}
inline void Subject::_internal_set_incarnation(uint64_t value) {
  
  _impl_.incarnation_ = value;
}
inline void Subject::set_incarnation(uint64_t value) {
  _internal_set_incarnation(value);
  // @@protoc_insertion_point(field_set:yoke.interface.v1.Subject.incarnation)
}

// -------------------------------------------------------------------

// Suspension

// string grade = 1;
inline void Suspension::clear_grade() {
  _impl_.grade_.ClearToEmpty();
}
inline const std::string& Suspension::grade() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.Suspension.grade)
  return _internal_grade();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Suspension::set_grade(ArgT0&& arg0, ArgT... args) {
 
 _impl_.grade_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:yoke.interface.v1.Suspension.grade)
}
inline std::string* Suspension::mutable_grade() {
  std::string* _s = _internal_mutable_grade();
  // @@protoc_insertion_point(field_mutable:yoke.interface.v1.Suspension.grade)
  return _s;
}
inline const std::string& Suspension::_internal_grade() const {
  return _impl_.grade_.Get();
}
inline void Suspension::_internal_set_grade(const std::string& value) {
  
  _impl_.grade_.Set(value, GetArenaForAllocation());
}
inline std::string* Suspension::_internal_mutable_grade() {
  
  return _impl_.grade_.Mutable(GetArenaForAllocation());
}
inline std::string* Suspension::release_grade() {
  // @@protoc_insertion_point(field_release:yoke.interface.v1.Suspension.grade)
  return _impl_.grade_.Release();
}
inline void Suspension::set_allocated_grade(std::string* grade) {
  if (grade != nullptr) {
    
  } else {
    
  }
  _impl_.grade_.SetAllocated(grade, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.grade_.IsDefault()) {
    _impl_.grade_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:yoke.interface.v1.Suspension.grade)
}

// string by = 2;
inline void Suspension::clear_by() {
  _impl_.by_.ClearToEmpty();
}
inline const std::string& Suspension::by() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.Suspension.by)
  return _internal_by();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Suspension::set_by(ArgT0&& arg0, ArgT... args) {
 
 _impl_.by_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:yoke.interface.v1.Suspension.by)
}
inline std::string* Suspension::mutable_by() {
  std::string* _s = _internal_mutable_by();
  // @@protoc_insertion_point(field_mutable:yoke.interface.v1.Suspension.by)
  return _s;
}
inline const std::string& Suspension::_internal_by() const {
  return _impl_.by_.Get();
}
inline void Suspension::_internal_set_by(const std::string& value) {
  
  _impl_.by_.Set(value, GetArenaForAllocation());
}
inline std::string* Suspension::_internal_mutable_by() {
  
  return _impl_.by_.Mutable(GetArenaForAllocation());
}
inline std::string* Suspension::release_by() {
  // @@protoc_insertion_point(field_release:yoke.interface.v1.Suspension.by)
  return _impl_.by_.Release();
}
inline void Suspension::set_allocated_by(std::string* by) {
  if (by != nullptr) {
    
  } else {
    
  }
  _impl_.by_.SetAllocated(by, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.by_.IsDefault()) {
    _impl_.by_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:yoke.interface.v1.Suspension.by)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace interface
}  // namespace yoke

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::yoke::interface::v1::Code> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::yoke::interface::v1::Code>() {
  return ::yoke::interface::v1::Code_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_yoke_2finterface_2fv1_2fcodes_2eproto
