// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yoke/interface/v1/interface.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_yoke_2finterface_2fv1_2finterface_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_yoke_2finterface_2fv1_2finterface_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "yoke/interface/v1/codes.pb.h"
#include "yoke/interface/v1/events.pb.h"
#include "yoke/interface/v1/operations.pb.h"
#include "yoke/interface/v1/records.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_yoke_2finterface_2fv1_2finterface_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_yoke_2finterface_2fv1_2finterface_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_yoke_2finterface_2fv1_2finterface_2eproto;
namespace yoke {
namespace interface {
namespace v1 {
class Cancel;
struct CancelDefaultTypeInternal;
extern CancelDefaultTypeInternal _Cancel_default_instance_;
class ClientFrame;
struct ClientFrameDefaultTypeInternal;
extern ClientFrameDefaultTypeInternal _ClientFrame_default_instance_;
class Completion;
struct CompletionDefaultTypeInternal;
extern CompletionDefaultTypeInternal _Completion_default_instance_;
class CoreFrame;
struct CoreFrameDefaultTypeInternal;
extern CoreFrameDefaultTypeInternal _CoreFrame_default_instance_;
class Opening;
struct OpeningDefaultTypeInternal;
extern OpeningDefaultTypeInternal _Opening_default_instance_;
class StreamDelivery;
struct StreamDeliveryDefaultTypeInternal;
extern StreamDeliveryDefaultTypeInternal _StreamDelivery_default_instance_;
}  // namespace v1
}  // namespace interface
}  // namespace yoke
PROTOBUF_NAMESPACE_OPEN
template<> ::yoke::interface::v1::Cancel* Arena::CreateMaybeMessage<::yoke::interface::v1::Cancel>(Arena*);
template<> ::yoke::interface::v1::ClientFrame* Arena::CreateMaybeMessage<::yoke::interface::v1::ClientFrame>(Arena*);
template<> ::yoke::interface::v1::Completion* Arena::CreateMaybeMessage<::yoke::interface::v1::Completion>(Arena*);
template<> ::yoke::interface::v1::CoreFrame* Arena::CreateMaybeMessage<::yoke::interface::v1::CoreFrame>(Arena*);
template<> ::yoke::interface::v1::Opening* Arena::CreateMaybeMessage<::yoke::interface::v1::Opening>(Arena*);
template<> ::yoke::interface::v1::StreamDelivery* Arena::CreateMaybeMessage<::yoke::interface::v1::StreamDelivery>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace yoke {
namespace interface {
namespace v1 {

enum Completion_By : int {
  Completion_By_BY_UNSPECIFIED = 0,
  Completion_By_BY_CALLER = 1,
  Completion_By_BY_CORE = 2,
  Completion_By_Completion_By_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  Completion_By_Completion_By_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool Completion_By_IsValid(int value);
constexpr Completion_By Completion_By_By_MIN = Completion_By_BY_UNSPECIFIED;
constexpr Completion_By Completion_By_By_MAX = Completion_By_BY_CORE;
constexpr int Completion_By_By_ARRAYSIZE = Completion_By_By_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Completion_By_descriptor();
template<typename T>
inline const std::string& Completion_By_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Completion_By>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Completion_By_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Completion_By_descriptor(), enum_t_value);
}
inline bool Completion_By_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Completion_By* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Completion_By>(
    Completion_By_descriptor(), name, value);
}
// ===================================================================

class ClientFrame final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yoke.interface.v1.ClientFrame) */ {
 public:
  inline ClientFrame() : ClientFrame(nullptr) {}
  ~ClientFrame() override;
  explicit PROTOBUF_CONSTEXPR ClientFrame(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ClientFrame(const ClientFrame& from);
  ClientFrame(ClientFrame&& from) noexcept
    : ClientFrame() {
    *this = ::std::move(from);
  }

  inline ClientFrame& operator=(const ClientFrame& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientFrame& operator=(ClientFrame&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClientFrame& default_instance() {
    return *internal_default_instance();
  }
  enum CarriesCase {
    kRequest = 2,
    kCancel = 3,
    CARRIES_NOT_SET = 0,
  };

  static inline const ClientFrame* internal_default_instance() {
    return reinterpret_cast<const ClientFrame*>(
               &_ClientFrame_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ClientFrame& a, ClientFrame& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientFrame* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClientFrame* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ClientFrame* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ClientFrame>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ClientFrame& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ClientFrame& from) {
    ClientFrame::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClientFrame* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yoke.interface.v1.ClientFrame";
  }
  protected:
  explicit ClientFrame(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCallFieldNumber = 1,
    kRequestFieldNumber = 2,
    kCancelFieldNumber = 3,
  };
  // string call = 1;
  void clear_call();
  const std::string& call() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_call(ArgT0&& arg0, ArgT... args);
  std::string* mutable_call();
  PROTOBUF_NODISCARD std::string* release_call();
  void set_allocated_call(std::string* call);
  private:
  const std::string& _internal_call() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_call(const std::string& value);
  std::string* _internal_mutable_call();
  public:

  // .yoke.interface.v1.Request request = 2;
  bool has_request() const;
  private:
  bool _internal_has_request() const;
  public:
  void clear_request();
  const ::yoke::interface::v1::Request& request() const;
  PROTOBUF_NODISCARD ::yoke::interface::v1::Request* release_request();
  ::yoke::interface::v1::Request* mutable_request();
  void set_allocated_request(::yoke::interface::v1::Request* request);
  private:
  const ::yoke::interface::v1::Request& _internal_request() const;
  ::yoke::interface::v1::Request* _internal_mutable_request();
  public:
  void unsafe_arena_set_allocated_request(
      ::yoke::interface::v1::Request* request);
  ::yoke::interface::v1::Request* unsafe_arena_release_request();

  // .yoke.interface.v1.Cancel cancel = 3;
  bool has_cancel() const;
  private:
  bool _internal_has_cancel() const;
  public:
  void clear_cancel();
  const ::yoke::interface::v1::Cancel& cancel() const;
  PROTOBUF_NODISCARD ::yoke::interface::v1::Cancel* release_cancel();
  ::yoke::interface::v1::Cancel* mutable_cancel();
  void set_allocated_cancel(::yoke::interface::v1::Cancel* cancel);
  private:
  const ::yoke::interface::v1::Cancel& _internal_cancel() const;
  ::yoke::interface::v1::Cancel* _internal_mutable_cancel();
  public:
  void unsafe_arena_set_allocated_cancel(
      ::yoke::interface::v1::Cancel* cancel);
  ::yoke::interface::v1::Cancel* unsafe_arena_release_cancel();

  void clear_carries();
  CarriesCase carries_case() const;
  // @@protoc_insertion_point(class_scope:yoke.interface.v1.ClientFrame)
 private:
  class _Internal;
  void set_has_request();
  void set_has_cancel();

  inline bool has_carries() const;
  inline void clear_has_carries();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr call_;
    union CarriesUnion {
      constexpr CarriesUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::yoke::interface::v1::Request* request_;
      ::yoke::interface::v1::Cancel* cancel_;
    } carries_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_yoke_2finterface_2fv1_2finterface_2eproto;
};
// -------------------------------------------------------------------

class Cancel final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:yoke.interface.v1.Cancel) */ {
 public:
  inline Cancel() : Cancel(nullptr) {}
  explicit PROTOBUF_CONSTEXPR Cancel(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Cancel(const Cancel& from);
  Cancel(Cancel&& from) noexcept
    : Cancel() {
    *this = ::std::move(from);
  }

  inline Cancel& operator=(const Cancel& from) {
    CopyFrom(from);
    return *this;
  }
  inline Cancel& operator=(Cancel&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Cancel& default_instance() {
    return *internal_default_instance();
  }
  static inline const Cancel* internal_default_instance() {
    return reinterpret_cast<const Cancel*>(
               &_Cancel_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Cancel& a, Cancel& b) {
    a.Swap(&b);
  }
  inline void Swap(Cancel* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Cancel* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Cancel* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Cancel>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const Cancel& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const Cancel& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yoke.interface.v1.Cancel";
  }
  protected:
  explicit Cancel(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:yoke.interface.v1.Cancel)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_yoke_2finterface_2fv1_2finterface_2eproto;
};
// -------------------------------------------------------------------

class CoreFrame final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yoke.interface.v1.CoreFrame) */ {
 public:
  inline CoreFrame() : CoreFrame(nullptr) {}
  ~CoreFrame() override;
  explicit PROTOBUF_CONSTEXPR CoreFrame(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CoreFrame(const CoreFrame& from);
  CoreFrame(CoreFrame&& from) noexcept
    : CoreFrame() {
    *this = ::std::move(from);
  }

  inline CoreFrame& operator=(const CoreFrame& from) {
    CopyFrom(from);
    return *this;
  }
  inline CoreFrame& operator=(CoreFrame&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CoreFrame& default_instance() {
    return *internal_default_instance();
  }
  enum CarriesCase {
    kOpening = 2,
    kAnswer = 3,
    kEvent = 4,
    kDelivery = 5,
    kRefusal = 6,
    kCompletion = 7,
    CARRIES_NOT_SET = 0,
  };

  static inline const CoreFrame* internal_default_instance() {
    return reinterpret_cast<const CoreFrame*>(
               &_CoreFrame_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(CoreFrame& a, CoreFrame& b) {
    a.Swap(&b);
  }
  inline void Swap(CoreFrame* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CoreFrame* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CoreFrame* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CoreFrame>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CoreFrame& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CoreFrame& from) {
    CoreFrame::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CoreFrame* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yoke.interface.v1.CoreFrame";
  }
  protected:
  explicit CoreFrame(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCallFieldNumber = 1,
    kOpeningFieldNumber = 2,
    kAnswerFieldNumber = 3,
    kEventFieldNumber = 4,
    kDeliveryFieldNumber = 5,
    kRefusalFieldNumber = 6,
    kCompletionFieldNumber = 7,
  };
  // string call = 1;
  void clear_call();
  const std::string& call() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_call(ArgT0&& arg0, ArgT... args);
  std::string* mutable_call();
  PROTOBUF_NODISCARD std::string* release_call();
  void set_allocated_call(std::string* call);
  private:
  const std::string& _internal_call() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_call(const std::string& value);
  std::string* _internal_mutable_call();
  public:

  // .yoke.interface.v1.Opening opening = 2;
  bool has_opening() const;
  private:
  bool _internal_has_opening() const;
  public:
  void clear_opening();
  const ::yoke::interface::v1::Opening& opening() const;
  PROTOBUF_NODISCARD ::yoke::interface::v1::Opening* release_opening();
  ::yoke::interface::v1::Opening* mutable_opening();
  void set_allocated_opening(::yoke::interface::v1::Opening* opening);
  private:
  const ::yoke::interface::v1::Opening& _internal_opening() const;
  ::yoke::interface::v1::Opening* _internal_mutable_opening();
  public:
  void unsafe_arena_set_allocated_opening(
      ::yoke::interface::v1::Opening* opening);
  ::yoke::interface::v1::Opening* unsafe_arena_release_opening();

  // .yoke.interface.v1.Response answer = 3;
  bool has_answer() const;
  private:
  bool _internal_has_answer() const;
  public:
  void clear_answer();
  const ::yoke::interface::v1::Response& answer() const;
  PROTOBUF_NODISCARD ::yoke::interface::v1::Response* release_answer();
  ::yoke::interface::v1::Response* mutable_answer();
  void set_allocated_answer(::yoke::interface::v1::Response* answer);
  private:
  const ::yoke::interface::v1::Response& _internal_answer() const;
  ::yoke::interface::v1::Response* _internal_mutable_answer();
  public:
  void unsafe_arena_set_allocated_answer(
      ::yoke::interface::v1::Response* answer);
  ::yoke::interface::v1::Response* unsafe_arena_release_answer();

  // .yoke.interface.v1.Event event = 4;
  bool has_event() const;
  private:
  bool _internal_has_event() const;
  public:
  void clear_event();
  const ::yoke::interface::v1::Event& event() const;
  PROTOBUF_NODISCARD ::yoke::interface::v1::Event* release_event();
  ::yoke::interface::v1::Event* mutable_event();
  void set_allocated_event(::yoke::interface::v1::Event* event);
  private:
  const ::yoke::interface::v1::Event& _internal_event() const;
  ::yoke::interface::v1::Event* _internal_mutable_event();
  public:
  void unsafe_arena_set_allocated_event(
      ::yoke::interface::v1::Event* event);
  ::yoke::interface::v1::Event* unsafe_arena_release_event();

  // .yoke.interface.v1.StreamDelivery delivery = 5;
  bool has_delivery() const;
  private:
  bool _internal_has_delivery() const;
  public:
  void clear_delivery();
  const ::yoke::interface::v1::StreamDelivery& delivery() const;
  PROTOBUF_NODISCARD ::yoke::interface::v1::StreamDelivery* release_delivery();
  ::yoke::interface::v1::StreamDelivery* mutable_delivery();
  void set_allocated_delivery(::yoke::interface::v1::StreamDelivery* delivery);
  private:
  const ::yoke::interface::v1::StreamDelivery& _internal_delivery() const;
  ::yoke::interface::v1::StreamDelivery* _internal_mutable_delivery();
  public:
  void unsafe_arena_set_allocated_delivery(
      ::yoke::interface::v1::StreamDelivery* delivery);
  ::yoke::interface::v1::StreamDelivery* unsafe_arena_release_delivery();

  // .yoke.interface.v1.Refusal refusal = 6;
  bool has_refusal() const;
  private:
  bool _internal_has_refusal() const;
  public:
  void clear_refusal();
  const ::yoke::interface::v1::Refusal& refusal() const;
  PROTOBUF_NODISCARD ::yoke::interface::v1::Refusal* release_refusal();
  ::yoke::interface::v1::Refusal* mutable_refusal();
  void set_allocated_refusal(::yoke::interface::v1::Refusal* refusal);
  private:
  const ::yoke::interface::v1::Refusal& _internal_refusal() const;
  ::yoke::interface::v1::Refusal* _internal_mutable_refusal();
  public:
  void unsafe_arena_set_allocated_refusal(
      ::yoke::interface::v1::Refusal* refusal);
  ::yoke::interface::v1::Refusal* unsafe_arena_release_refusal();

  // .yoke.interface.v1.Completion completion = 7;
  bool has_completion() const;
  private:
  bool _internal_has_completion() const;
  public:
  void clear_completion();
  const ::yoke::interface::v1::Completion& completion() const;
  PROTOBUF_NODISCARD ::yoke::interface::v1::Completion* release_completion();
  ::yoke::interface::v1::Completion* mutable_completion();
  void set_allocated_completion(::yoke::interface::v1::Completion* completion);
  private:
  const ::yoke::interface::v1::Completion& _internal_completion() const;
  ::yoke::interface::v1::Completion* _internal_mutable_completion();
  public:
  void unsafe_arena_set_allocated_completion(
      ::yoke::interface::v1::Completion* completion);
  ::yoke::interface::v1::Completion* unsafe_arena_release_completion();

  void clear_carries();
  CarriesCase carries_case() const;
  // @@protoc_insertion_point(class_scope:yoke.interface.v1.CoreFrame)
 private:
  class _Internal;
  void set_has_opening();
  void set_has_answer();
  void set_has_event();
  void set_has_delivery();
  void set_has_refusal();
  void set_has_completion();

  inline bool has_carries() const;
  inline void clear_has_carries();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr call_;
    union CarriesUnion {
      constexpr CarriesUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::yoke::interface::v1::Opening* opening_;
      ::yoke::interface::v1::Response* answer_;
      ::yoke::interface::v1::Event* event_;
      ::yoke::interface::v1::StreamDelivery* delivery_;
      ::yoke::interface::v1::Refusal* refusal_;
      ::yoke::interface::v1::Completion* completion_;
    } carries_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_yoke_2finterface_2fv1_2finterface_2eproto;
};
// -------------------------------------------------------------------

class Opening final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yoke.interface.v1.Opening) */ {
 public:
  inline Opening() : Opening(nullptr) {}
  ~Opening() override;
  explicit PROTOBUF_CONSTEXPR Opening(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Opening(const Opening& from);
  Opening(Opening&& from) noexcept
    : Opening() {
    *this = ::std::move(from);
  }

  inline Opening& operator=(const Opening& from) {
    CopyFrom(from);
    return *this;
  }
  inline Opening& operator=(Opening&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Opening& default_instance() {
    return *internal_default_instance();
  }
  static inline const Opening* internal_default_instance() {
    return reinterpret_cast<const Opening*>(
               &_Opening_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Opening& a, Opening& b) {
    a.Swap(&b);
  }
  inline void Swap(Opening* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Opening* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Opening* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Opening>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Opening& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Opening& from) {
    Opening::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Opening* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yoke.interface.v1.Opening";
  }
  protected:
  explicit Opening(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSubscriptionFieldNumber = 2,
    kPictureFieldNumber = 1,
    kVersionFieldNumber = 3,
  };
  // string subscription = 2;
  void clear_subscription();
  const std::string& subscription() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_subscription(ArgT0&& arg0, ArgT... args);
  std::string* mutable_subscription();
  PROTOBUF_NODISCARD std::string* release_subscription();
  void set_allocated_subscription(std::string* subscription);
  private:
  const std::string& _internal_subscription() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_subscription(const std::string& value);
  std::string* _internal_mutable_subscription();
  public:

  // .yoke.interface.v1.Snapshot picture = 1;
  bool has_picture() const;
  private:
  bool _internal_has_picture() const;
  public:
  void clear_picture();
  const ::yoke::interface::v1::Snapshot& picture() const;
  PROTOBUF_NODISCARD ::yoke::interface::v1::Snapshot* release_picture();
  ::yoke::interface::v1::Snapshot* mutable_picture();
  void set_allocated_picture(::yoke::interface::v1::Snapshot* picture);
  private:
  const ::yoke::interface::v1::Snapshot& _internal_picture() const;
  ::yoke::interface::v1::Snapshot* _internal_mutable_picture();
  public:
  void unsafe_arena_set_allocated_picture(
      ::yoke::interface::v1::Snapshot* picture);
  ::yoke::interface::v1::Snapshot* unsafe_arena_release_picture();

  // uint32 version = 3;
  void clear_version();
  uint32_t version() const;
  void set_version(uint32_t value);
  private:
  uint32_t _internal_version() const;
  void _internal_set_version(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:yoke.interface.v1.Opening)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr subscription_;
    ::yoke::interface::v1::Snapshot* picture_;
    uint32_t version_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_yoke_2finterface_2fv1_2finterface_2eproto;
};
// -------------------------------------------------------------------

class StreamDelivery final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yoke.interface.v1.StreamDelivery) */ {
 public:
  inline StreamDelivery() : StreamDelivery(nullptr) {}
  ~StreamDelivery() override;
  explicit PROTOBUF_CONSTEXPR StreamDelivery(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  StreamDelivery(const StreamDelivery& from);
  StreamDelivery(StreamDelivery&& from) noexcept
    : StreamDelivery() {
    *this = ::std::move(from);
  }

  inline StreamDelivery& operator=(const StreamDelivery& from) {
    CopyFrom(from);
    return *this;
  }
  inline StreamDelivery& operator=(StreamDelivery&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const StreamDelivery& default_instance() {
    return *internal_default_instance();
  }
  static inline const StreamDelivery* internal_default_instance() {
    return reinterpret_cast<const StreamDelivery*>(
               &_StreamDelivery_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(StreamDelivery& a, StreamDelivery& b) {
    a.Swap(&b);
  }
  inline void Swap(StreamDelivery* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(StreamDelivery* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  StreamDelivery* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<StreamDelivery>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const StreamDelivery& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const StreamDelivery& from) {
    StreamDelivery::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(StreamDelivery* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yoke.interface.v1.StreamDelivery";
  }
  protected:
  explicit StreamDelivery(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDeliveryFieldNumber = 1,
    kPayloadFieldNumber = 4,
    kSequenceFieldNumber = 2,
    kSentAtFieldNumber = 3,
  };
  // string delivery = 1;
  void clear_delivery();
  const std::string& delivery() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_delivery(ArgT0&& arg0, ArgT... args);
  std::string* mutable_delivery();
  PROTOBUF_NODISCARD std::string* release_delivery();
  void set_allocated_delivery(std::string* delivery);
  private:
  const std::string& _internal_delivery() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_delivery(const std::string& value);
  std::string* _internal_mutable_delivery();
  public:

  // bytes payload = 4;
  void clear_payload();
  const std::string& payload() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_payload(ArgT0&& arg0, ArgT... args);
  std::string* mutable_payload();
  PROTOBUF_NODISCARD std::string* release_payload();
  void set_allocated_payload(std::string* payload);
  private:
  const std::string& _internal_payload() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_payload(const std::string& value);
  std::string* _internal_mutable_payload();
  public:

  // uint64 sequence = 2;
  void clear_sequence();
  uint64_t sequence() const;
  void set_sequence(uint64_t value);
  private:
  uint64_t _internal_sequence() const;
  void _internal_set_sequence(uint64_t value);
  public:

  // uint64 sent_at = 3;
  void clear_sent_at();
  uint64_t sent_at() const;
  void set_sent_at(uint64_t value);
  private:
  uint64_t _internal_sent_at() const;
  void _internal_set_sent_at(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:yoke.interface.v1.StreamDelivery)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr delivery_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr payload_;
    uint64_t sequence_;
    uint64_t sent_at_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_yoke_2finterface_2fv1_2finterface_2eproto;
};
// -------------------------------------------------------------------

class Completion final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yoke.interface.v1.Completion) */ {
 public:
  inline Completion() : Completion(nullptr) {}
  ~Completion() override;
  explicit PROTOBUF_CONSTEXPR Completion(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Completion(const Completion& from);
  Completion(Completion&& from) noexcept
    : Completion() {
    *this = ::std::move(from);
  }

  inline Completion& operator=(const Completion& from) {
    CopyFrom(from);
    return *this;
  }
  inline Completion& operator=(Completion&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Completion& default_instance() {
    return *internal_default_instance();
  }
  static inline const Completion* internal_default_instance() {
    return reinterpret_cast<const Completion*>(
               &_Completion_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(Completion& a, Completion& b) {
    a.Swap(&b);
  }
  inline void Swap(Completion* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Completion* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Completion* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Completion>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Completion& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Completion& from) {
    Completion::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Completion* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yoke.interface.v1.Completion";
  }
  protected:
  explicit Completion(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Completion_By By;
  static constexpr By BY_UNSPECIFIED =
    Completion_By_BY_UNSPECIFIED;
  static constexpr By BY_CALLER =
    Completion_By_BY_CALLER;
  static constexpr By BY_CORE =
    Completion_By_BY_CORE;
  static inline bool By_IsValid(int value) {
    return Completion_By_IsValid(value);
  }
  static constexpr By By_MIN =
    Completion_By_By_MIN;
  static constexpr By By_MAX =
    Completion_By_By_MAX;
  static constexpr int By_ARRAYSIZE =
    Completion_By_By_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  By_descriptor() {
    return Completion_By_descriptor();
  }
  template<typename T>
  static inline const std::string& By_Name(T enum_t_value) {
    static_assert(::std::is_same<T, By>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function By_Name.");
    return Completion_By_Name(enum_t_value);
  }
  static inline bool By_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      By* value) {
    return Completion_By_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kByFieldNumber = 1,
  };
  // .yoke.interface.v1.Completion.By by = 1;
  void clear_by();
  ::yoke::interface::v1::Completion_By by() const;
  void set_by(::yoke::interface::v1::Completion_By value);
  private:
  ::yoke::interface::v1::Completion_By _internal_by() const;
  void _internal_set_by(::yoke::interface::v1::Completion_By value);
  public:

  // @@protoc_insertion_point(class_scope:yoke.interface.v1.Completion)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int by_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_yoke_2finterface_2fv1_2finterface_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ClientFrame

// string call = 1;
inline void ClientFrame::clear_call() {
  _impl_.call_.ClearToEmpty();
}
inline const std::string& ClientFrame::call() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.ClientFrame.call)
  return _internal_call();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ClientFrame::set_call(ArgT0&& arg0, ArgT... args) {
 
 _impl_.call_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:yoke.interface.v1.ClientFrame.call)
}
inline std::string* ClientFrame::mutable_call() {
  std::string* _s = _internal_mutable_call();
  // @@protoc_insertion_point(field_mutable:yoke.interface.v1.ClientFrame.call)
  return _s;
}
inline const std::string& ClientFrame::_internal_call() const {
  return _impl_.call_.Get();
}
inline void ClientFrame::_internal_set_call(const std::string& value) {
  
  _impl_.call_.Set(value, GetArenaForAllocation());
}
inline std::string* ClientFrame::_internal_mutable_call() {
  
  return _impl_.call_.Mutable(GetArenaForAllocation());
}
inline std::string* ClientFrame::release_call() {
  // @@protoc_insertion_point(field_release:yoke.interface.v1.ClientFrame.call)
  return _impl_.call_.Release();
}
inline void ClientFrame::set_allocated_call(std::string* call) {
  if (call != nullptr) {
    
  } else {
    
  }
  _impl_.call_.SetAllocated(call, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.call_.IsDefault()) {
    _impl_.call_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:yoke.interface.v1.ClientFrame.call)
}

// .yoke.interface.v1.Request request = 2;
inline bool ClientFrame::_internal_has_request() const {
  return carries_case() == kRequest;
}
inline bool ClientFrame::has_request() const {
  return _internal_has_request();
}
inline void ClientFrame::set_has_request() {
  _impl_._oneof_case_[0] = kRequest;
}
inline ::yoke::interface::v1::Request* ClientFrame::release_request() {
  // @@protoc_insertion_point(field_release:yoke.interface.v1.ClientFrame.request)
  if (_internal_has_request()) {
    clear_has_carries();
    ::yoke::interface::v1::Request* temp = _impl_.carries_.request_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.carries_.request_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::yoke::interface::v1::Request& ClientFrame::_internal_request() const {
  return _internal_has_request()
      ? *_impl_.carries_.request_
      : reinterpret_cast< ::yoke::interface::v1::Request&>(::yoke::interface::v1::_Request_default_instance_);
}
inline const ::yoke::interface::v1::Request& ClientFrame::request() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.ClientFrame.request)
  return _internal_request();
}
inline ::yoke::interface::v1::Request* ClientFrame::unsafe_arena_release_request() {
  // @@protoc_insertion_point(field_unsafe_arena_release:yoke.interface.v1.ClientFrame.request)
  if (_internal_has_request()) {
    clear_has_carries();
    ::yoke::interface::v1::Request* temp = _impl_.carries_.request_;
    _impl_.carries_.request_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ClientFrame::unsafe_arena_set_allocated_request(::yoke::interface::v1::Request* request) {
  clear_carries();
  if (request) {
    set_has_request();
    _impl_.carries_.request_ = request;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:yoke.interface.v1.ClientFrame.request)
}
inline ::yoke::interface::v1::Request* ClientFrame::_internal_mutable_request() {
  if (!_internal_has_request()) {
    clear_carries();
    set_has_request();
    _impl_.carries_.request_ = CreateMaybeMessage< ::yoke::interface::v1::Request >(GetArenaForAllocation());
  }
  return _impl_.carries_.request_;
}
inline ::yoke::interface::v1::Request* ClientFrame::mutable_request() {
  ::yoke::interface::v1::Request* _msg = _internal_mutable_request();
  // @@protoc_insertion_point(field_mutable:yoke.interface.v1.ClientFrame.request)
  return _msg;
}

// .yoke.interface.v1.Cancel cancel = 3;
inline bool ClientFrame::_internal_has_cancel() const {
  return carries_case() == kCancel;
}
inline bool ClientFrame::has_cancel() const {
  return _internal_has_cancel();
}
inline void ClientFrame::set_has_cancel() {
  _impl_._oneof_case_[0] = kCancel;
}
inline void ClientFrame::clear_cancel() {
  if (_internal_has_cancel()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.carries_.cancel_;
    }
    clear_has_carries();
  }
}
inline ::yoke::interface::v1::Cancel* ClientFrame::release_cancel() {
  // @@protoc_insertion_point(field_release:yoke.interface.v1.ClientFrame.cancel)
  if (_internal_has_cancel()) {
    clear_has_carries();
    ::yoke::interface::v1::Cancel* temp = _impl_.carries_.cancel_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.carries_.cancel_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::yoke::interface::v1::Cancel& ClientFrame::_internal_cancel() const {
  return _internal_has_cancel()
      ? *_impl_.carries_.cancel_
      : reinterpret_cast< ::yoke::interface::v1::Cancel&>(::yoke::interface::v1::_Cancel_default_instance_);
}
inline const ::yoke::interface::v1::Cancel& ClientFrame::cancel() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.ClientFrame.cancel)
  return _internal_cancel();
}
inline ::yoke::interface::v1::Cancel* ClientFrame::unsafe_arena_release_cancel() {
  // @@protoc_insertion_point(field_unsafe_arena_release:yoke.interface.v1.ClientFrame.cancel)
  if (_internal_has_cancel()) {
    clear_has_carries();
    ::yoke::interface::v1::Cancel* temp = _impl_.carries_.cancel_;
    _impl_.carries_.cancel_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ClientFrame::unsafe_arena_set_allocated_cancel(::yoke::interface::v1::Cancel* cancel) {
  clear_carries();
  if (cancel) {
    set_has_cancel();
    _impl_.carries_.cancel_ = cancel;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:yoke.interface.v1.ClientFrame.cancel)
}
inline ::yoke::interface::v1::Cancel* ClientFrame::_internal_mutable_cancel() {
  if (!_internal_has_cancel()) {
    clear_carries();
    set_has_cancel();
    _impl_.carries_.cancel_ = CreateMaybeMessage< ::yoke::interface::v1::Cancel >(GetArenaForAllocation());
  }
  return _impl_.carries_.cancel_;
}
inline ::yoke::interface::v1::Cancel* ClientFrame::mutable_cancel() {
  ::yoke::interface::v1::Cancel* _msg = _internal_mutable_cancel();
  // @@protoc_insertion_point(field_mutable:yoke.interface.v1.ClientFrame.cancel)
  return _msg;
}

inline bool ClientFrame::has_carries() const {
  return carries_case() != CARRIES_NOT_SET;
}
inline void ClientFrame::clear_has_carries() {
  _impl_._oneof_case_[0] = CARRIES_NOT_SET;
}
inline ClientFrame::CarriesCase ClientFrame::carries_case() const {
  return ClientFrame::CarriesCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// Cancel

// -------------------------------------------------------------------

// CoreFrame

// string call = 1;
inline void CoreFrame::clear_call() {
  _impl_.call_.ClearToEmpty();
}
inline const std::string& CoreFrame::call() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.CoreFrame.call)
  return _internal_call();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CoreFrame::set_call(ArgT0&& arg0, ArgT... args) {
 
 _impl_.call_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:yoke.interface.v1.CoreFrame.call)
}
inline std::string* CoreFrame::mutable_call() {
  std::string* _s = _internal_mutable_call();
  // @@protoc_insertion_point(field_mutable:yoke.interface.v1.CoreFrame.call)
  return _s;
}
inline const std::string& CoreFrame::_internal_call() const {
  return _impl_.call_.Get();
}
inline void CoreFrame::_internal_set_call(const std::string& value) {
  
  _impl_.call_.Set(value, GetArenaForAllocation());
}
inline std::string* CoreFrame::_internal_mutable_call() {
  
  return _impl_.call_.Mutable(GetArenaForAllocation());
}
inline std::string* CoreFrame::release_call() {
  // @@protoc_insertion_point(field_release:yoke.interface.v1.CoreFrame.call)
  return _impl_.call_.Release();
}
inline void CoreFrame::set_allocated_call(std::string* call) {
  if (call != nullptr) {
    
  } else {
    
  }
  _impl_.call_.SetAllocated(call, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.call_.IsDefault()) {
    _impl_.call_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:yoke.interface.v1.CoreFrame.call)
}

// .yoke.interface.v1.Opening opening = 2;
inline bool CoreFrame::_internal_has_opening() const {
  return carries_case() == kOpening;
}
inline bool CoreFrame::has_opening() const {
  return _internal_has_opening();
}
inline void CoreFrame::set_has_opening() {
  _impl_._oneof_case_[0] = kOpening;
}
inline void CoreFrame::clear_opening() {
  if (_internal_has_opening()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.carries_.opening_;
    }
    clear_has_carries();
  }
}
inline ::yoke::interface::v1::Opening* CoreFrame::release_opening() {
  // @@protoc_insertion_point(field_release:yoke.interface.v1.CoreFrame.opening)
  if (_internal_has_opening()) {
    clear_has_carries();
    ::yoke::interface::v1::Opening* temp = _impl_.carries_.opening_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.carries_.opening_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::yoke::interface::v1::Opening& CoreFrame::_internal_opening() const {
  return _internal_has_opening()
      ? *_impl_.carries_.opening_
      : reinterpret_cast< ::yoke::interface::v1::Opening&>(::yoke::interface::v1::_Opening_default_instance_);
}
inline const ::yoke::interface::v1::Opening& CoreFrame::opening() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.CoreFrame.opening)
  return _internal_opening();
}
inline ::yoke::interface::v1::Opening* CoreFrame::unsafe_arena_release_opening() {
  // @@protoc_insertion_point(field_unsafe_arena_release:yoke.interface.v1.CoreFrame.opening)
  if (_internal_has_opening()) {
    clear_has_carries();
    ::yoke::interface::v1::Opening* temp = _impl_.carries_.opening_;
    _impl_.carries_.opening_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void CoreFrame::unsafe_arena_set_allocated_opening(::yoke::interface::v1::Opening* opening) {
  clear_carries();
  if (opening) {
    set_has_opening();
    _impl_.carries_.opening_ = opening;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:yoke.interface.v1.CoreFrame.opening)
}
inline ::yoke::interface::v1::Opening* CoreFrame::_internal_mutable_opening() {
  if (!_internal_has_opening()) {
    clear_carries();
    set_has_opening();
    _impl_.carries_.opening_ = CreateMaybeMessage< ::yoke::interface::v1::Opening >(GetArenaForAllocation());
  }
  return _impl_.carries_.opening_;
}
inline ::yoke::interface::v1::Opening* CoreFrame::mutable_opening() {
  ::yoke::interface::v1::Opening* _msg = _internal_mutable_opening();
  // @@protoc_insertion_point(field_mutable:yoke.interface.v1.CoreFrame.opening)
  return _msg;
}

// .yoke.interface.v1.Response answer = 3;
inline bool CoreFrame::_internal_has_answer() const {
  return carries_case() == kAnswer;
}
inline bool CoreFrame::has_answer() const {
  return _internal_has_answer();
}
inline void CoreFrame::set_has_answer() {
  _impl_._oneof_case_[0] = kAnswer;
}
inline ::yoke::interface::v1::Response* CoreFrame::release_answer() {
  // @@protoc_insertion_point(field_release:yoke.interface.v1.CoreFrame.answer)
  if (_internal_has_answer()) {
    clear_has_carries();
    ::yoke::interface::v1::Response* temp = _impl_.carries_.answer_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.carries_.answer_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::yoke::interface::v1::Response& CoreFrame::_internal_answer() const {
  return _internal_has_answer()
      ? *_impl_.carries_.answer_
      : reinterpret_cast< ::yoke::interface::v1::Response&>(::yoke::interface::v1::_Response_default_instance_);
}
inline const ::yoke::interface::v1::Response& CoreFrame::answer() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.CoreFrame.answer)
  return _internal_answer();
}
inline ::yoke::interface::v1::Response* CoreFrame::unsafe_arena_release_answer() {
  // @@protoc_insertion_point(field_unsafe_arena_release:yoke.interface.v1.CoreFrame.answer)
  if (_internal_has_answer()) {
    clear_has_carries();
    ::yoke::interface::v1::Response* temp = _impl_.carries_.answer_;
    _impl_.carries_.answer_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void CoreFrame::unsafe_arena_set_allocated_answer(::yoke::interface::v1::Response* answer) {
  clear_carries();
  if (answer) {
    set_has_answer();
    _impl_.carries_.answer_ = answer;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:yoke.interface.v1.CoreFrame.answer)
}
inline ::yoke::interface::v1::Response* CoreFrame::_internal_mutable_answer() {
  if (!_internal_has_answer()) {
    clear_carries();
    set_has_answer();
    _impl_.carries_.answer_ = CreateMaybeMessage< ::yoke::interface::v1::Response >(GetArenaForAllocation());
  }
  return _impl_.carries_.answer_;
}
inline ::yoke::interface::v1::Response* CoreFrame::mutable_answer() {
  ::yoke::interface::v1::Response* _msg = _internal_mutable_answer();
  // @@protoc_insertion_point(field_mutable:yoke.interface.v1.CoreFrame.answer)
  return _msg;
}

// .yoke.interface.v1.Event event = 4;
inline bool CoreFrame::_internal_has_event() const {
  return carries_case() == kEvent;
}
inline bool CoreFrame::has_event() const {
  return _internal_has_event();
}
inline void CoreFrame::set_has_event() {
  _impl_._oneof_case_[0] = kEvent;
}
inline ::yoke::interface::v1::Event* CoreFrame::release_event() {
  // @@protoc_insertion_point(field_release:yoke.interface.v1.CoreFrame.event)
  if (_internal_has_event()) {
    clear_has_carries();
    ::yoke::interface::v1::Event* temp = _impl_.carries_.event_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.carries_.event_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::yoke::interface::v1::Event& CoreFrame::_internal_event() const {
  return _internal_has_event()
      ? *_impl_.carries_.event_
      : reinterpret_cast< ::yoke::interface::v1::Event&>(::yoke::interface::v1::_Event_default_instance_);
}
inline const ::yoke::interface::v1::Event& CoreFrame::event() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.CoreFrame.event)
  return _internal_event();
}
inline ::yoke::interface::v1::Event* CoreFrame::unsafe_arena_release_event() {
  // @@protoc_insertion_point(field_unsafe_arena_release:yoke.interface.v1.CoreFrame.event)
  if (_internal_has_event()) {
    clear_has_carries();
    ::yoke::interface::v1::Event* temp = _impl_.carries_.event_;
    _impl_.carries_.event_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void CoreFrame::unsafe_arena_set_allocated_event(::yoke::interface::v1::Event* event) {
  clear_carries();
  if (event) {
    set_has_event();
    _impl_.carries_.event_ = event;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:yoke.interface.v1.CoreFrame.event)
}
inline ::yoke::interface::v1::Event* CoreFrame::_internal_mutable_event() {
  if (!_internal_has_event()) {
    clear_carries();
    set_has_event();
    _impl_.carries_.event_ = CreateMaybeMessage< ::yoke::interface::v1::Event >(GetArenaForAllocation());
  }
  return _impl_.carries_.event_;
}
inline ::yoke::interface::v1::Event* CoreFrame::mutable_event() {
  ::yoke::interface::v1::Event* _msg = _internal_mutable_event();
  // @@protoc_insertion_point(field_mutable:yoke.interface.v1.CoreFrame.event)
  return _msg;
}

// .yoke.interface.v1.StreamDelivery delivery = 5;
inline bool CoreFrame::_internal_has_delivery() const {
  return carries_case() == kDelivery;
}
inline bool CoreFrame::has_delivery() const {
  return _internal_has_delivery();
}
inline void CoreFrame::set_has_delivery() {
  _impl_._oneof_case_[0] = kDelivery;
}
inline void CoreFrame::clear_delivery() {
  if (_internal_has_delivery()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.carries_.delivery_;
    }
    clear_has_carries();
  }
}
inline ::yoke::interface::v1::StreamDelivery* CoreFrame::release_delivery() {
  // @@protoc_insertion_point(field_release:yoke.interface.v1.CoreFrame.delivery)
  if (_internal_has_delivery()) {
    clear_has_carries();
    ::yoke::interface::v1::StreamDelivery* temp = _impl_.carries_.delivery_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.carries_.delivery_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::yoke::interface::v1::StreamDelivery& CoreFrame::_internal_delivery() const {
  return _internal_has_delivery()
      ? *_impl_.carries_.delivery_
      : reinterpret_cast< ::yoke::interface::v1::StreamDelivery&>(::yoke::interface::v1::_StreamDelivery_default_instance_);
}
inline const ::yoke::interface::v1::StreamDelivery& CoreFrame::delivery() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.CoreFrame.delivery)
  return _internal_delivery();
}
inline ::yoke::interface::v1::StreamDelivery* CoreFrame::unsafe_arena_release_delivery() {
  // @@protoc_insertion_point(field_unsafe_arena_release:yoke.interface.v1.CoreFrame.delivery)
  if (_internal_has_delivery()) {
    clear_has_carries();
    ::yoke::interface::v1::StreamDelivery* temp = _impl_.carries_.delivery_;
    _impl_.carries_.delivery_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void CoreFrame::unsafe_arena_set_allocated_delivery(::yoke::interface::v1::StreamDelivery* delivery) {
  clear_carries();
  if (delivery) {
    set_has_delivery();
    _impl_.carries_.delivery_ = delivery;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:yoke.interface.v1.CoreFrame.delivery)
}
inline ::yoke::interface::v1::StreamDelivery* CoreFrame::_internal_mutable_delivery() {
  if (!_internal_has_delivery()) {
    clear_carries();
    set_has_delivery();
    _impl_.carries_.delivery_ = CreateMaybeMessage< ::yoke::interface::v1::StreamDelivery >(GetArenaForAllocation());
  }
  return _impl_.carries_.delivery_;
}
inline ::yoke::interface::v1::StreamDelivery* CoreFrame::mutable_delivery() {
  ::yoke::interface::v1::StreamDelivery* _msg = _internal_mutable_delivery();
  // @@protoc_insertion_point(field_mutable:yoke.interface.v1.CoreFrame.delivery)
  return _msg;
}

// .yoke.interface.v1.Refusal refusal = 6;
inline bool CoreFrame::_internal_has_refusal() const {
  return carries_case() == kRefusal;
}
inline bool CoreFrame::has_refusal() const {
  return _internal_has_refusal();
}
inline void CoreFrame::set_has_refusal() {
  _impl_._oneof_case_[0] = kRefusal;
}
inline ::yoke::interface::v1::Refusal* CoreFrame::release_refusal() {
  // @@protoc_insertion_point(field_release:yoke.interface.v1.CoreFrame.refusal)
  if (_internal_has_refusal()) {
    clear_has_carries();
    ::yoke::interface::v1::Refusal* temp = _impl_.carries_.refusal_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.carries_.refusal_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::yoke::interface::v1::Refusal& CoreFrame::_internal_refusal() const {
  return _internal_has_refusal()
      ? *_impl_.carries_.refusal_
      : reinterpret_cast< ::yoke::interface::v1::Refusal&>(::yoke::interface::v1::_Refusal_default_instance_);
}
inline const ::yoke::interface::v1::Refusal& CoreFrame::refusal() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.CoreFrame.refusal)
  return _internal_refusal();
}
inline ::yoke::interface::v1::Refusal* CoreFrame::unsafe_arena_release_refusal() {
  // @@protoc_insertion_point(field_unsafe_arena_release:yoke.interface.v1.CoreFrame.refusal)
  if (_internal_has_refusal()) {
    clear_has_carries();
    ::yoke::interface::v1::Refusal* temp = _impl_.carries_.refusal_;
    _impl_.carries_.refusal_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void CoreFrame::unsafe_arena_set_allocated_refusal(::yoke::interface::v1::Refusal* refusal) {
  clear_carries();
  if (refusal) {
    set_has_refusal();
    _impl_.carries_.refusal_ = refusal;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:yoke.interface.v1.CoreFrame.refusal)
}
inline ::yoke::interface::v1::Refusal* CoreFrame::_internal_mutable_refusal() {
  if (!_internal_has_refusal()) {
    clear_carries();
    set_has_refusal();
    _impl_.carries_.refusal_ = CreateMaybeMessage< ::yoke::interface::v1::Refusal >(GetArenaForAllocation());
  }
  return _impl_.carries_.refusal_;
}
inline ::yoke::interface::v1::Refusal* CoreFrame::mutable_refusal() {
  ::yoke::interface::v1::Refusal* _msg = _internal_mutable_refusal();
  // @@protoc_insertion_point(field_mutable:yoke.interface.v1.CoreFrame.refusal)
  return _msg;
}

// .yoke.interface.v1.Completion completion = 7;
inline bool CoreFrame::_internal_has_completion() const {
  return carries_case() == kCompletion;
}
inline bool CoreFrame::has_completion() const {
  return _internal_has_completion();
}
inline void CoreFrame::set_has_completion() {
  _impl_._oneof_case_[0] = kCompletion;
}
inline void CoreFrame::clear_completion() {
  if (_internal_has_completion()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.carries_.completion_;
    }
    clear_has_carries();
  }
}
inline ::yoke::interface::v1::Completion* CoreFrame::release_completion() {
  // @@protoc_insertion_point(field_release:yoke.interface.v1.CoreFrame.completion)
  if (_internal_has_completion()) {
    clear_has_carries();
    ::yoke::interface::v1::Completion* temp = _impl_.carries_.completion_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.carries_.completion_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::yoke::interface::v1::Completion& CoreFrame::_internal_completion() const {
  return _internal_has_completion()
      ? *_impl_.carries_.completion_
      : reinterpret_cast< ::yoke::interface::v1::Completion&>(::yoke::interface::v1::_Completion_default_instance_);
}
inline const ::yoke::interface::v1::Completion& CoreFrame::completion() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.CoreFrame.completion)
  return _internal_completion();
}
inline ::yoke::interface::v1::Completion* CoreFrame::unsafe_arena_release_completion() {
  // @@protoc_insertion_point(field_unsafe_arena_release:yoke.interface.v1.CoreFrame.completion)
  if (_internal_has_completion()) {
    clear_has_carries();
    ::yoke::interface::v1::Completion* temp = _impl_.carries_.completion_;
    _impl_.carries_.completion_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void CoreFrame::unsafe_arena_set_allocated_completion(::yoke::interface::v1::Completion* completion) {
  clear_carries();
  if (completion) {
    set_has_completion();
    _impl_.carries_.completion_ = completion;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:yoke.interface.v1.CoreFrame.completion)
}
inline ::yoke::interface::v1::Completion* CoreFrame::_internal_mutable_completion() {
  if (!_internal_has_completion()) {
    clear_carries();
    set_has_completion();
    _impl_.carries_.completion_ = CreateMaybeMessage< ::yoke::interface::v1::Completion >(GetArenaForAllocation());
  }
  return _impl_.carries_.completion_;
}
inline ::yoke::interface::v1::Completion* CoreFrame::mutable_completion() {
  ::yoke::interface::v1::Completion* _msg = _internal_mutable_completion();
  // @@protoc_insertion_point(field_mutable:yoke.interface.v1.CoreFrame.completion)
  return _msg;
}

inline bool CoreFrame::has_carries() const {
  return carries_case() != CARRIES_NOT_SET;
}
inline void CoreFrame::clear_has_carries() {
  _impl_._oneof_case_[0] = CARRIES_NOT_SET;
}
inline CoreFrame::CarriesCase CoreFrame::carries_case() const {
  return CoreFrame::CarriesCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// Opening

// .yoke.interface.v1.Snapshot picture = 1;
inline bool Opening::_internal_has_picture() const {
  return this != internal_default_instance() && _impl_.picture_ != nullptr;
}
inline bool Opening::has_picture() const {
  return _internal_has_picture();
}
inline const ::yoke::interface::v1::Snapshot& Opening::_internal_picture() const {
  const ::yoke::interface::v1::Snapshot* p = _impl_.picture_;
  return p != nullptr ? *p : reinterpret_cast<const ::yoke::interface::v1::Snapshot&>(
      ::yoke::interface::v1::_Snapshot_default_instance_);
}
inline const ::yoke::interface::v1::Snapshot& Opening::picture() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.Opening.picture)
  return _internal_picture();
}
inline void Opening::unsafe_arena_set_allocated_picture(
    ::yoke::interface::v1::Snapshot* picture) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.picture_);
  }
  _impl_.picture_ = picture;
  if (picture) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:yoke.interface.v1.Opening.picture)
}
inline ::yoke::interface::v1::Snapshot* Opening::release_picture() {
  
  ::yoke::interface::v1::Snapshot* temp = _impl_.picture_;
  _impl_.picture_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::yoke::interface::v1::Snapshot* Opening::unsafe_arena_release_picture() {
  // @@protoc_insertion_point(field_release:yoke.interface.v1.Opening.picture)
  
  ::yoke::interface::v1::Snapshot* temp = _impl_.picture_;
  _impl_.picture_ = nullptr;
  return temp;
}
inline ::yoke::interface::v1::Snapshot* Opening::_internal_mutable_picture() {
  
  if (_impl_.picture_ == nullptr) {
    auto* p = CreateMaybeMessage<::yoke::interface::v1::Snapshot>(GetArenaForAllocation());
    _impl_.picture_ = p;
  }
  return _impl_.picture_;
}
inline ::yoke::interface::v1::Snapshot* Opening::mutable_picture() {
  ::yoke::interface::v1::Snapshot* _msg = _internal_mutable_picture();
  // @@protoc_insertion_point(field_mutable:yoke.interface.v1.Opening.picture)
  return _msg;
}
inline void Opening::set_allocated_picture(::yoke::interface::v1::Snapshot* picture) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.picture_);
  }
  if (picture) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(picture));
    if (message_arena != submessage_arena) {
      picture = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, picture, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.picture_ = picture;
  // @@protoc_insertion_point(field_set_allocated:yoke.interface.v1.Opening.picture)
}

// string subscription = 2;
inline void Opening::clear_subscription() {
  _impl_.subscription_.ClearToEmpty();
}
inline const std::string& Opening::subscription() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.Opening.subscription)
  return _internal_subscription();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Opening::set_subscription(ArgT0&& arg0, ArgT... args) {
 
 _impl_.subscription_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:yoke.interface.v1.Opening.subscription)
}
inline std::string* Opening::mutable_subscription() {
  std::string* _s = _internal_mutable_subscription();
  // @@protoc_insertion_point(field_mutable:yoke.interface.v1.Opening.subscription)
  return _s;
}
inline const std::string& Opening::_internal_subscription() const {
  return _impl_.subscription_.Get();
}
inline void Opening::_internal_set_subscription(const std::string& value) {
  
  _impl_.subscription_.Set(value, GetArenaForAllocation());
}
inline std::string* Opening::_internal_mutable_subscription() {
  
  return _impl_.subscription_.Mutable(GetArenaForAllocation());
}
inline std::string* Opening::release_subscription() {
  // @@protoc_insertion_point(field_release:yoke.interface.v1.Opening.subscription)
  return _impl_.subscription_.Release();
}
inline void Opening::set_allocated_subscription(std::string* subscription) {
  if (subscription != nullptr) {
    
  } else {
    
  }
  _impl_.subscription_.SetAllocated(subscription, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.subscription_.IsDefault()) {
    _impl_.subscription_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:yoke.interface.v1.Opening.subscription)
}

// uint32 version = 3;
inline void Opening::clear_version() {
  _impl_.version_ = 0u;
}
inline uint32_t Opening::_internal_version() const {
  return _impl_.version_;
}
inline uint32_t Opening::version() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.Opening.version)
  return _internal_version();
}
inline void Opening::_internal_set_version(uint32_t value) {
  
  _impl_.version_ = value;
}
inline void Opening::set_version(uint32_t value) {
  _internal_set_version(value);
  // @@protoc_insertion_point(field_set:yoke.interface.v1.Opening.version)
}

// -------------------------------------------------------------------

// StreamDelivery

// string delivery = 1;
inline void StreamDelivery::clear_delivery() {
  _impl_.delivery_.ClearToEmpty();
}
inline const std::string& StreamDelivery::delivery() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.StreamDelivery.delivery)
  return _internal_delivery();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void StreamDelivery::set_delivery(ArgT0&& arg0, ArgT... args) {
 
 _impl_.delivery_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:yoke.interface.v1.StreamDelivery.delivery)
}
inline std::string* StreamDelivery::mutable_delivery() {
  std::string* _s = _internal_mutable_delivery();
  // @@protoc_insertion_point(field_mutable:yoke.interface.v1.StreamDelivery.delivery)
  return _s;
}
inline const std::string& StreamDelivery::_internal_delivery() const {
  return _impl_.delivery_.Get();
}
inline void StreamDelivery::_internal_set_delivery(const std::string& value) {
  
  _impl_.delivery_.Set(value, GetArenaForAllocation());
}
inline std::string* StreamDelivery::_internal_mutable_delivery() {
  
  return _impl_.delivery_.Mutable(GetArenaForAllocation());
}
inline std::string* StreamDelivery::release_delivery() {
  // @@protoc_insertion_point(field_release:yoke.interface.v1.StreamDelivery.delivery)
  return _impl_.delivery_.Release();
}
inline void StreamDelivery::set_allocated_delivery(std::string* delivery) {
  if (delivery != nullptr) {
    
  } else {
    
  }
  _impl_.delivery_.SetAllocated(delivery, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.delivery_.IsDefault()) {
    _impl_.delivery_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:yoke.interface.v1.StreamDelivery.delivery)
}

// uint64 sequence = 2;
inline void StreamDelivery::clear_sequence() {
  _impl_.sequence_ = uint64_t{0u};
}
inline uint64_t StreamDelivery::_internal_sequence() const {
  return _impl_.sequence_;
}
inline uint64_t StreamDelivery::sequence() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.StreamDelivery.sequence)
  return _internal_sequence();
}
inline void StreamDelivery::_internal_set_sequence(uint64_t value) {
  
  _impl_.sequence_ = value;
}
inline void StreamDelivery::set_sequence(uint64_t value) {
  _internal_set_sequence(value);
  // @@protoc_insertion_point(field_set:yoke.interface.v1.StreamDelivery.sequence)
}

// uint64 sent_at = 3;
inline void StreamDelivery::clear_sent_at() {
  _impl_.sent_at_ = uint64_t{0u};
}
inline uint64_t StreamDelivery::_internal_sent_at() const {
  return _impl_.sent_at_;
}
inline uint64_t StreamDelivery::sent_at() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.StreamDelivery.sent_at)
  return _internal_sent_at();
}
inline void StreamDelivery::_internal_set_sent_at(uint64_t value) {
  
  _impl_.sent_at_ = value;
}
inline void StreamDelivery::set_sent_at(uint64_t value) {
  _internal_set_sent_at(value);
  // @@protoc_insertion_point(field_set:yoke.interface.v1.StreamDelivery.sent_at)
}

// bytes payload = 4;
inline void StreamDelivery::clear_payload() {
  _impl_.payload_.ClearToEmpty();
}
inline const std::string& StreamDelivery::payload() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.StreamDelivery.payload)
  return _internal_payload();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void StreamDelivery::set_payload(ArgT0&& arg0, ArgT... args) {
 
 _impl_.payload_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:yoke.interface.v1.StreamDelivery.payload)
}
inline std::string* StreamDelivery::mutable_payload() {
  std::string* _s = _internal_mutable_payload();
  // @@protoc_insertion_point(field_mutable:yoke.interface.v1.StreamDelivery.payload)
  return _s;
}
inline const std::string& StreamDelivery::_internal_payload() const {
  return _impl_.payload_.Get();
}
inline void StreamDelivery::_internal_set_payload(const std::string& value) {
  
  _impl_.payload_.Set(value, GetArenaForAllocation());
}
inline std::string* StreamDelivery::_internal_mutable_payload() {
  
  return _impl_.payload_.Mutable(GetArenaForAllocation());
}
inline std::string* StreamDelivery::release_payload() {
  // @@protoc_insertion_point(field_release:yoke.interface.v1.StreamDelivery.payload)
  return _impl_.payload_.Release();
}
inline void StreamDelivery::set_allocated_payload(std::string* payload) {
  if (payload != nullptr) {
    
  } else {
    
  }
  _impl_.payload_.SetAllocated(payload, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.payload_.IsDefault()) {
    _impl_.payload_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:yoke.interface.v1.StreamDelivery.payload)
}

// -------------------------------------------------------------------

// Completion

// .yoke.interface.v1.Completion.By by = 1;
inline void Completion::clear_by() {
  _impl_.by_ = 0;
}
inline ::yoke::interface::v1::Completion_By Completion::_internal_by() const {
  return static_cast< ::yoke::interface::v1::Completion_By >(_impl_.by_);
}
inline ::yoke::interface::v1::Completion_By Completion::by() const {
  // @@protoc_insertion_point(field_get:yoke.interface.v1.Completion.by)
  return _internal_by();
}
inline void Completion::_internal_set_by(::yoke::interface::v1::Completion_By value) {
  
  _impl_.by_ = value;
}
inline void Completion::set_by(::yoke::interface::v1::Completion_By value) {
  _internal_set_by(value);
  // @@protoc_insertion_point(field_set:yoke.interface.v1.Completion.by)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace interface
}  // namespace yoke

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::yoke::interface::v1::Completion_By> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::yoke::interface::v1::Completion_By>() {
  return ::yoke::interface::v1::Completion_By_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_yoke_2finterface_2fv1_2finterface_2eproto
