// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: yoke/interface/v1/interface.proto

#include "yoke/interface/v1/interface.pb.h"
#include "yoke/interface/v1/interface.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace yoke {
namespace interface {
namespace v1 {

static const char* Interface_method_names[] = {
  "/yoke.interface.v1.Interface/Attach",
};

std::unique_ptr< Interface::Stub> Interface::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Interface::Stub> stub(new Interface::Stub(channel, options));
  return stub;
}

Interface::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Attach_(Interface_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::yoke::interface::v1::ClientFrame, ::yoke::interface::v1::CoreFrame>* Interface::Stub::AttachRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::yoke::interface::v1::ClientFrame, ::yoke::interface::v1::CoreFrame>::Create(channel_.get(), rpcmethod_Attach_, context);
}

void Interface::Stub::async::Attach(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::yoke::interface::v1::ClientFrame,::yoke::interface::v1::CoreFrame>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::yoke::interface::v1::ClientFrame,::yoke::interface::v1::CoreFrame>::Create(stub_->channel_.get(), stub_->rpcmethod_Attach_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::yoke::interface::v1::ClientFrame, ::yoke::interface::v1::CoreFrame>* Interface::Stub::AsyncAttachRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::yoke::interface::v1::ClientFrame, ::yoke::interface::v1::CoreFrame>::Create(channel_.get(), cq, rpcmethod_Attach_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::yoke::interface::v1::ClientFrame, ::yoke::interface::v1::CoreFrame>* Interface::Stub::PrepareAsyncAttachRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::yoke::interface::v1::ClientFrame, ::yoke::interface::v1::CoreFrame>::Create(channel_.get(), cq, rpcmethod_Attach_, context, false, nullptr);
}

Interface::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Interface_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< Interface::Service, ::yoke::interface::v1::ClientFrame, ::yoke::interface::v1::CoreFrame>(
          [](Interface::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::yoke::interface::v1::CoreFrame,
             ::yoke::interface::v1::ClientFrame>* stream) {
               return service->Attach(ctx, stream);
             }, this)));
}

Interface::Service::~Service() {
}

::grpc::Status Interface::Service::Attach(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::yoke::interface::v1::CoreFrame, ::yoke::interface::v1::ClientFrame>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace yoke
}  // namespace interface
}  // namespace v1

