// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: yoke/interface/v1/interface.proto
// Original file comments:
// The typed projection: one service and one method, because an interface is always attached. Opening
// the stream is attaching; one stream carries many calls, each correlated by an identity the caller
// chose, and each ending with exactly one completion.
#ifndef GRPC_yoke_2finterface_2fv1_2finterface_2eproto__INCLUDED
#define GRPC_yoke_2finterface_2fv1_2finterface_2eproto__INCLUDED

#include "yoke/interface/v1/interface.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace yoke {
namespace interface {
namespace v1 {

class Interface final {
 public:
  static constexpr char const* service_full_name() {
    return "yoke.interface.v1.Interface";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::yoke::interface::v1::ClientFrame, ::yoke::interface::v1::CoreFrame>> Attach(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::yoke::interface::v1::ClientFrame, ::yoke::interface::v1::CoreFrame>>(AttachRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::yoke::interface::v1::ClientFrame, ::yoke::interface::v1::CoreFrame>> AsyncAttach(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::yoke::interface::v1::ClientFrame, ::yoke::interface::v1::CoreFrame>>(AsyncAttachRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::yoke::interface::v1::ClientFrame, ::yoke::interface::v1::CoreFrame>> PrepareAsyncAttach(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::yoke::interface::v1::ClientFrame, ::yoke::interface::v1::CoreFrame>>(PrepareAsyncAttachRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Attach(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::yoke::interface::v1::ClientFrame,::yoke::interface::v1::CoreFrame>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::yoke::interface::v1::ClientFrame, ::yoke::interface::v1::CoreFrame>* AttachRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::yoke::interface::v1::ClientFrame, ::yoke::interface::v1::CoreFrame>* AsyncAttachRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::yoke::interface::v1::ClientFrame, ::yoke::interface::v1::CoreFrame>* PrepareAsyncAttachRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::yoke::interface::v1::ClientFrame, ::yoke::interface::v1::CoreFrame>> Attach(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::yoke::interface::v1::ClientFrame, ::yoke::interface::v1::CoreFrame>>(AttachRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::yoke::interface::v1::ClientFrame, ::yoke::interface::v1::CoreFrame>> AsyncAttach(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::yoke::interface::v1::ClientFrame, ::yoke::interface::v1::CoreFrame>>(AsyncAttachRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::yoke::interface::v1::ClientFrame, ::yoke::interface::v1::CoreFrame>> PrepareAsyncAttach(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::yoke::interface::v1::ClientFrame, ::yoke::interface::v1::CoreFrame>>(PrepareAsyncAttachRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Attach(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::yoke::interface::v1::ClientFrame,::yoke::interface::v1::CoreFrame>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::yoke::interface::v1::ClientFrame, ::yoke::interface::v1::CoreFrame>* AttachRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::yoke::interface::v1::ClientFrame, ::yoke::interface::v1::CoreFrame>* AsyncAttachRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::yoke::interface::v1::ClientFrame, ::yoke::interface::v1::CoreFrame>* PrepareAsyncAttachRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Attach_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Attach(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::yoke::interface::v1::CoreFrame, ::yoke::interface::v1::ClientFrame>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_Attach : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Attach() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Attach() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Attach(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::yoke::interface::v1::CoreFrame, ::yoke::interface::v1::ClientFrame>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAttach(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::yoke::interface::v1::CoreFrame, ::yoke::interface::v1::ClientFrame>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Attach<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Attach : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Attach() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::yoke::interface::v1::ClientFrame, ::yoke::interface::v1::CoreFrame>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->Attach(context); }));
    }
    ~WithCallbackMethod_Attach() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Attach(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::yoke::interface::v1::CoreFrame, ::yoke::interface::v1::ClientFrame>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::yoke::interface::v1::ClientFrame, ::yoke::interface::v1::CoreFrame>* Attach(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_Attach<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Attach : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Attach() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Attach() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Attach(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::yoke::interface::v1::CoreFrame, ::yoke::interface::v1::ClientFrame>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Attach : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Attach() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Attach() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Attach(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::yoke::interface::v1::CoreFrame, ::yoke::interface::v1::ClientFrame>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAttach(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Attach : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Attach() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->Attach(context); }));
    }
    ~WithRawCallbackMethod_Attach() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Attach(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::yoke::interface::v1::CoreFrame, ::yoke::interface::v1::ClientFrame>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* Attach(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace v1
}  // namespace interface
}  // namespace yoke


#endif  // GRPC_yoke_2finterface_2fv1_2finterface_2eproto__INCLUDED
