// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: yoke/interface/v1/records.proto
// Original file comments:
// The one record the opening picture, a read and a subscription's snapshot are all made of, over the
// three subject kinds a channel observes. Every field is fixed for the life of the instance or maintained
// by a level.
#ifndef GRPC_yoke_2finterface_2fv1_2frecords_2eproto__INCLUDED
#define GRPC_yoke_2finterface_2fv1_2frecords_2eproto__INCLUDED

#include "yoke/interface/v1/records.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace yoke {
namespace interface {
namespace v1 {

}  // namespace v1
}  // namespace interface
}  // namespace yoke


#endif  // GRPC_yoke_2finterface_2fv1_2frecords_2eproto__INCLUDED
